import { LensDefinition } from './lens-types';
import { createAttribution, createUnlockMetadata } from '../shared/metadata';

export const LENSES_011_020: LensDefinition[] = [
{ id: 'lens-011', name: 'HDR Balance', specialty: 'hdr', description: 'Balanced high dynamic range optical response.', visualDescription: 'Controlled highlights and lifted shadows.', icon: 'icon-lens-011', previewKey: 'preview-lens-011', processingProfile: { dynamicRange: 48, highlights: -28, shadows: 32, clarity: 14, denoise: 18 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'high contrast', recommendedLighting: 'harsh', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(15, false) },
{ id: 'lens-012', name: 'Texture Fine', specialty: 'fine-texture', description: 'Fine texture microcontrast enhancement.', visualDescription: 'Visible surface texture without harsh edges.', icon: 'icon-lens-012', previewKey: 'preview-lens-012', processingProfile: { microcontrast: 30, clarity: 24, sharpening: 26, denoise: 12 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'texture', recommendedLighting: 'side light', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(15, false) },
{ id: 'lens-013', name: 'Edge Clarity', specialty: 'detail-sharpness', description: 'Optical edge sharpness emphasis.', visualDescription: 'Clearly sharper fine edges.', icon: 'icon-lens-013', previewKey: 'preview-lens-013', processingProfile: { sharpening: 36, clarity: 30, microcontrast: 24, contrast: 16 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'detail', recommendedLighting: 'any', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(15, false) },
{ id: 'lens-014', name: 'Natural Soft', specialty: 'soft-natural', description: 'Natural soft optical diffusion.', visualDescription: 'Gentle softness, subject remains recognizable.', icon: 'icon-lens-014', previewKey: 'preview-lens-014', processingProfile: { clarity: -12, denoise: 18, bloom: 14, temperature: 6, vibrance: 8 }, intensityRange: { min: 0, max: 100, default: 75 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'portraits', recommendedLighting: 'natural', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(0, true) },
{ id: 'lens-015', name: 'Golden Hour', specialty: 'golden-hour', description: 'Warm golden-hour optical rendering.', visualDescription: 'Warm temperature shift with soft clarity.', icon: 'icon-lens-015', previewKey: 'preview-lens-015', processingProfile: { temperature: 28, vibrance: 18, contrast: 18, shadows: 12, clarity: 10 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'outdoor', recommendedLighting: 'golden hour', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(12, false) },
{ id: 'lens-016', name: 'Blue Hour', specialty: 'blue-hour', description: 'Cool blue-hour optical rendering.', visualDescription: 'Cool temperature with evening contrast.', icon: 'icon-lens-016', previewKey: 'preview-lens-016', processingProfile: { temperature: -26, contrast: 20, clarity: 14, saturation: -6, vignette: 16 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'outdoor', recommendedLighting: 'blue hour', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(12, false) },
{ id: 'lens-017', name: 'Mist Veil', specialty: 'atmospheric', description: 'Atmospheric haze and soft depth.', visualDescription: 'Softer atmosphere, reduced micro-haze punch.', icon: 'icon-lens-017', previewKey: 'preview-lens-017', processingProfile: { atmosphere: -28, fade: 20, contrast: 8, temperature: -6, denoise: 10 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'landscape', recommendedLighting: 'overcast', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(12, false) },
{ id: 'lens-018', name: 'Motion Freeze', specialty: 'motion', description: 'Optical freeze clarity for motion subjects.', visualDescription: 'Sharper freeze-frame detail.', icon: 'icon-lens-018', previewKey: 'preview-lens-018', processingProfile: { sharpening: 30, clarity: 26, microcontrast: 20, contrast: 14, denoise: 10 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'action', recommendedLighting: 'any', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(15, false) },
{ id: 'lens-019', name: 'Travel Clean', specialty: 'travel', description: 'Clean travel optical clarity and vibrance.', visualDescription: 'Cleaner detail and balanced color.', icon: 'icon-lens-019', previewKey: 'preview-lens-019', processingProfile: { clarity: 20, sharpening: 16, vibrance: 16, contrast: 18, dynamicRange: 18, denoise: 12 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'travel', recommendedLighting: 'daylight', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(12, false) },
{ id: 'lens-020', name: 'Universal Clear', specialty: 'universal', description: 'General-purpose optical clarity lens.', visualDescription: 'Balanced clarity, sharpening, and range.', icon: 'icon-lens-020', previewKey: 'preview-lens-020', processingProfile: { clarity: 18, sharpening: 14, contrast: 14, denoise: 10, vibrance: 8, dynamicRange: 12 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'general', recommendedLighting: 'any', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(0, true) },
];
