import { LensDefinition } from './lens-types';
import { createAttribution, createUnlockMetadata } from '../shared/metadata';

export const LENSES_001_010: LensDefinition[] = [
{ id: 'lens-001', name: 'Night Whisper', specialty: 'low-light', description: 'Low-light shadow lift with controlled noise.', visualDescription: 'Brighter shadows, cleaner night detail.', icon: 'icon-lens-001', previewKey: 'preview-lens-001', processingProfile: { exposure: 14, shadows: 36, highlights: -12, denoise: 40, clarity: 14, microcontrast: 12, temperature: -8, saturation: 6, sharpening: 10, vignette: 12 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'night scenes', recommendedLighting: 'low light', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(0, true) },
{ id: 'lens-002', name: 'Deep Night', specialty: 'night', description: 'Deep night contrast with recovered shadows.', visualDescription: 'Darker skies, recovered shadow detail.', icon: 'icon-lens-002', previewKey: 'preview-lens-002', processingProfile: { exposure: 8, shadows: 28, highlights: -22, denoise: 34, clarity: 16, microcontrast: 14, temperature: -14, contrast: 16, vignette: 28, dynamicRange: 32 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'night city', recommendedLighting: 'night', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(0, true) },
{ id: 'lens-003', name: 'Starlight Edge', specialty: 'stars-sky', description: 'Edge clarity for stars and night skies.', visualDescription: 'Crisper star points and sky structure.', icon: 'icon-lens-003', previewKey: 'preview-lens-003', processingProfile: { exposure: 10, shadows: 18, contrast: 20, clarity: 28, microcontrast: 24, sharpening: 20, denoise: 22, temperature: -10, starSeparation: 50 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'sky', recommendedLighting: 'night', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(15, false) },
{ id: 'lens-004', name: 'Shadow Recover', specialty: 'dark-scenes', description: 'Aggressive shadow recovery and range.', visualDescription: 'Lifted shadows without flat midtones.', icon: 'icon-lens-004', previewKey: 'preview-lens-004', processingProfile: { exposure: 16, shadows: 40, highlights: -14, denoise: 28, dynamicRange: 42, clarity: 12 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'interiors', recommendedLighting: 'dim', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(15, false) },
{ id: 'lens-005', name: 'Soft Portrait', specialty: 'portrait', description: 'Soft optical portrait diffusion.', visualDescription: 'Softer skin, gentle bloom, natural subject.', icon: 'icon-lens-005', previewKey: 'preview-lens-005', processingProfile: { clarity: -16, denoise: 22, bloom: 18, temperature: 10, vibrance: 12, sharpening: 6 }, intensityRange: { min: 0, max: 100, default: 75 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'portraits', recommendedLighting: 'natural', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(0, true) },
{ id: 'lens-006', name: 'Vista Expand', specialty: 'landscape', description: 'Expanded landscape dynamic range and depth.', visualDescription: 'Wider tonal range and atmospheric depth.', icon: 'icon-lens-006', previewKey: 'preview-lens-006', processingProfile: { dynamicRange: 38, clarity: 22, microcontrast: 18, saturation: 12, sharpening: 16, atmosphere: 22 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'landscapes', recommendedLighting: 'daylight', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(15, false) },
{ id: 'lens-007', name: 'Structure Line', specialty: 'architecture', description: 'Architectural structure and edge emphasis.', visualDescription: 'Stronger lines and microcontrast.', icon: 'icon-lens-007', previewKey: 'preview-lens-007', processingProfile: { clarity: 32, microcontrast: 26, sharpening: 28, contrast: 18, saturation: -6 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'buildings', recommendedLighting: 'any', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(15, false) },
{ id: 'lens-008', name: 'Street Pulse', specialty: 'street', description: 'Street photography optical punch.', visualDescription: 'Gritty clarity and controlled vignette.', icon: 'icon-lens-008', previewKey: 'preview-lens-008', processingProfile: { contrast: 30, clarity: 26, microcontrast: 18, sharpening: 22, saturation: -10, denoise: 14, vignette: 22 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'street', recommendedLighting: 'mixed', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(15, false) },
{ id: 'lens-009', name: 'Culinary Warmth', specialty: 'food', description: 'Food-oriented warmth and microcontrast.', visualDescription: 'Appetizing warmth and texture.', icon: 'icon-lens-009', previewKey: 'preview-lens-009', processingProfile: { temperature: 18, saturation: 22, vibrance: 18, microcontrast: 20, sharpening: 16, clarity: 12, bloom: 10 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'food', recommendedLighting: 'warm', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(12, false) },
{ id: 'lens-010', name: 'Cinema Depth', specialty: 'cinematic', description: 'Cinematic optical contrast and depth.', visualDescription: 'Deeper contrast with vignette falloff.', icon: 'icon-lens-010', previewKey: 'preview-lens-010', processingProfile: { contrast: 28, clarity: 16, vignette: 34, temperature: -8, dynamicRange: 22, grain: 14 }, intensityRange: { min: 0, max: 100, default: 80 }, supportsPreview: true as const, supportsFullResolution: true as const, supportsCamera: false as const, recommendedSubjects: 'general', recommendedLighting: 'dramatic', developerNotes: '', attribution: createAttribution(), unlock: createUnlockMetadata(15, false) },
];
