import { LensDefinition } from './lens-types';
import { createAttribution, createUnlockMetadata } from '../shared/metadata';

export const LENSES_011_020: LensDefinition[] = [
  {id:'lens-011',name:'Warm Golden',specialty:'golden-hour',description:'Warm Golden — golden-hour warmth with soft highlight rolloff.',visualDescription:'Golden hour warmth, soft rolloff.',icon:'icon-lens-011',previewKey:'preview-lens-011',processingProfile:{temperature:28,tint:6,highlights:-14,bloom:14,saturation:12,contrast:14},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Golden hour',recommendedSubjects:'Outdoor portraits, landscapes',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'lens-012',name:'Blue Hour',specialty:'blue-hour',description:'Blue Hour — cool blue-hour atmosphere and lifted shadows.',visualDescription:'Blue hour cool, atmospheric.',icon:'icon-lens-012',previewKey:'preview-lens-012',processingProfile:{temperature:-30,atmosphere:22,shadows:24,contrast:16,saturation:8},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Blue hour',recommendedSubjects:'Cityscapes, water',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'lens-013',name:'HDR Balance',specialty:'hdr',description:'HDR Balance — expanded dynamic range with natural local contrast.',visualDescription:'Balanced HDR, natural local contrast.',icon:'icon-lens-013',previewKey:'preview-lens-013',processingProfile:{dynamicRange:52,shadows:28,highlights:-22,clarity:16,contrast:12},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'High contrast scenes',recommendedSubjects:'Interiors, landscapes',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'lens-014',name:'Architecture Line',specialty:'architecture',description:'Architecture Line — edge clarity and neutral color for buildings.',visualDescription:'Clean architectural lines.',icon:'icon-lens-014',previewKey:'preview-lens-014',processingProfile:{clarity:28,sharpening:24,microcontrast:22,saturation:-6,contrast:18},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Daylight',recommendedSubjects:'Buildings, interiors',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'lens-015',name:'Street Snap',specialty:'street',description:'Street Snap — fast street character with grit and punch.',visualDescription:'Street grit and punch.',icon:'icon-lens-015',previewKey:'preview-lens-015',processingProfile:{contrast:30,clarity:20,grain:16,sharpening:18,saturation:10,vignette:16},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Available light',recommendedSubjects:'Street scenes',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'lens-016',name:'Fine Texture',specialty:'fine-texture',description:'Fine Texture — micro-detail and surface texture emphasis.',visualDescription:'Fine surface texture.',icon:'icon-lens-016',previewKey:'preview-lens-016',processingProfile:{microcontrast:32,clarity:26,sharpening:22,contrast:14,denoise:6},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Even side light',recommendedSubjects:'Texture, fabric, product',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'lens-017',name:'Atmospheric Haze',specialty:'atmospheric',description:'Atmospheric Haze — depth haze and soft distance separation.',visualDescription:'Atmospheric depth haze.',icon:'icon-lens-017',previewKey:'preview-lens-017',processingProfile:{atmosphere:32,softBlur:10,fade:14,contrast:-8,shadows:12},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Overcast / mist',recommendedSubjects:'Landscapes, forests',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'lens-018',name:'Motion Freeze',specialty:'motion',description:'Motion Freeze — high sharpness and contrast for action freeze.',visualDescription:'Action freeze, high snap.',icon:'icon-lens-018',previewKey:'preview-lens-018',processingProfile:{sharpening:32,clarity:24,contrast:26,microcontrast:20,saturation:8},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Bright',recommendedSubjects:'Sports, action',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'lens-019',name:'Travel Clear',specialty:'travel',description:'Travel Clear — balanced clarity and natural color for travel.',visualDescription:'Clear travel, natural color.',icon:'icon-lens-019',previewKey:'preview-lens-019',processingProfile:{clarity:20,vibrance:18,contrast:16,sharpening:14,shadows:12},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Daylight',recommendedSubjects:'Travel, documentary',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'lens-020',name:'Universal Balance',specialty:'universal',description:'Universal Balance — neutral optical balance for general use.',visualDescription:'Neutral optical balance.',icon:'icon-lens-020',previewKey:'preview-lens-020',processingProfile:{contrast:12,clarity:12,sharpening:12,vibrance:8,dynamicRange:20},intensityRange:{min:0,max:100,default:80},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Any',recommendedSubjects:'General',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(0,true)},
];
