import { LensDefinition } from './lens-types';
import { createAttribution, createUnlockMetadata } from '../shared/metadata';

export const LENSES_001_010: LensDefinition[] = [
  {id:'lens-001',name:'Portrait Soft',specialty:'portrait',description:'Portrait Soft — subject separation with gentle background softness and skin-friendly rendering.',visualDescription:'Soft subject separation, natural skin.',icon:'icon-lens-001',previewKey:'preview-lens-001',processingProfile:{softBlur:14,clarity:-8,sharpening:10,shadows:16,temperature:6,bloom:10,microcontrast:8},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Soft natural or window light',recommendedSubjects:'Portraits, headshots',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(0,true)},
  {id:'lens-002',name:'Portrait Sharp',specialty:'portrait',description:'Portrait Sharp — crisp eye/edge detail with controlled background presence.',visualDescription:'Crisp edges, clear eyes, controlled bokeh feel.',icon:'icon-lens-002',previewKey:'preview-lens-002',processingProfile:{sharpening:28,clarity:22,microcontrast:20,contrast:16,softBlur:4},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Bright directional',recommendedSubjects:'Portraits needing detail',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'lens-003',name:'Night Lift',specialty:'night',description:'Night Lift — shadow recovery and low-light lift with controlled noise.',visualDescription:'Lifted shadows, usable night detail.',icon:'icon-lens-003',previewKey:'preview-lens-003',processingProfile:{shadows:36,dynamicRange:42,denoise:28,exposure:8,contrast:14,temperature:-6},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Low light / night',recommendedSubjects:'Night scenes, city lights',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'lens-004',name:'Night Crisp',specialty:'night',description:'Night Crisp — sharper night detail with microcontrast and cool tone.',visualDescription:'Crisp night edges, cool clarity.',icon:'icon-lens-004',previewKey:'preview-lens-004',processingProfile:{sharpening:26,clarity:24,microcontrast:22,temperature:-12,shadows:20,denoise:16},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Urban night',recommendedSubjects:'Streets, architecture at night',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'lens-005',name:'Landscape Depth',specialty:'landscape',description:'Landscape Depth — depth and atmosphere with midtone clarity.',visualDescription:'Landscape depth, clear midtones.',icon:'icon-lens-005',previewKey:'preview-lens-005',processingProfile:{clarity:26,atmosphere:18,contrast:22,vibrance:14,vignette:14,sharpening:16},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Daylight / golden hour',recommendedSubjects:'Landscapes, vistas',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'lens-006',name:'Landscape Wide',specialty:'landscape',description:'Landscape Wide — open dynamic range and sky-friendly highlights.',visualDescription:'Open DR, protected skies.',icon:'icon-lens-006',previewKey:'preview-lens-006',processingProfile:{dynamicRange:48,highlights:-18,shadows:22,clarity:18,contrast:14},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Bright outdoor',recommendedSubjects:'Wide landscapes',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'lens-007',name:'Cinematic Grade',specialty:'cinematic',description:'Cinematic Grade — filmic contrast, subtle teal-orange split, vignette.',visualDescription:'Filmic contrast, cinematic grade.',icon:'icon-lens-007',previewKey:'preview-lens-007',processingProfile:{contrast:28,splitToning:{shadowsHue:200,shadowsSaturation:22,highlightsHue:35,highlightsSaturation:24,balance:0},vignette:26,fade:10,grain:10},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Any dramatic',recommendedSubjects:'Narrative, film stills',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'lens-008',name:'Food Pop',specialty:'food',description:'Food Pop — appetizing saturation, microcontrast, and warm highlights.',visualDescription:'Food pop, appetizing color.',icon:'icon-lens-008',previewKey:'preview-lens-008',processingProfile:{saturation:24,vibrance:22,clarity:18,temperature:10,sharpening:16,highlights:-8},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Soft key + fill',recommendedSubjects:'Food, tabletop',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'lens-009',name:'Sharp Detail',specialty:'detail-sharpness',description:'Sharp Detail — maximum edge and micro-detail recovery.',visualDescription:'Maximum edge detail, micro-sharp.',icon:'icon-lens-009',previewKey:'preview-lens-009',processingProfile:{sharpening:36,clarity:30,microcontrast:28,contrast:18,denoise:8},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Bright even',recommendedSubjects:'Texture, product, architecture',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'lens-010',name:'Soft Natural',specialty:'soft-natural',description:'Soft Natural — optical softness without muddy blur; gentle glow.',visualDescription:'Optical softness, gentle glow.',icon:'icon-lens-010',previewKey:'preview-lens-010',processingProfile:{softBlur:18,bloom:16,clarity:-10,contrast:8,temperature:4,fade:8},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:true as const,supportsLivePreview:true,supportsVideo:false,recommendedLighting:'Soft diffused',recommendedSubjects:'Portraits, lifestyle',developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
];
