/**
 * Shared server-side History persistence for new generations.
 *
 * Architecture (storage-light):
 * - Do NOT copy generated media into Vercel Blob, Cloudflare R2, or Supabase Storage.
 * - Persist the fal.ai (provider) source URL + full History metadata only.
 * - retained_as_history is driven by user_settings.history_enabled (missing row = ON).
 * - User-facing delivery may go through Motio2edit resolvers; permanent reference is the source URL.
 * - Idempotent when generationId is provided (upsert on id).
 * - Never create History rows with empty/null output URLs.
 */

import type { SupabaseClient } from "@supabase/supabase-js";

export type HistoryStorageProvider = "fal" | "provider" | "supabase" | "r2" | "blob";

export type RetainDecision = {
  retain: boolean;
  /** Always fal/provider for new generations — no Motio2edit media copy. */
  storage_provider: HistoryStorageProvider | null;
};

/**
 * Authoritative History toggle. Missing user_settings row → true (History ON).
 */
export async function readHistoryEnabled(
  supabaseAdmin: SupabaseClient,
  userId: string,
): Promise<boolean> {
  try {
    const { data, error } = await supabaseAdmin
      .from("user_settings")
      .select("history_enabled")
      .eq("user_id", userId)
      .maybeSingle();
    if (error) {
      console.warn("[history-persist] user_settings read:", error.message);
      return true;
    }
    if (!data) return true;
    if ((data as { history_enabled?: unknown }).history_enabled === false) {
      return false;
    }
    return true;
  } catch (e) {
    console.warn("[history-persist] user_settings exception:", e);
    return true;
  }
}

/**
 * Retain decision only — no R2/Blob provider selection for generated History media.
 */
export async function callShouldRetainAsHistory(
  supabaseAdmin: SupabaseClient,
  userId: string,
  _isPrivate: boolean,
): Promise<RetainDecision> {
  const historyEnabled = await readHistoryEnabled(supabaseAdmin, userId);
  if (!historyEnabled) {
    return { retain: false, storage_provider: null };
  }
  return { retain: true, storage_provider: "fal" };
}

export type PersistGenerationInput = {
  supabaseAdmin: SupabaseClient;
  userId: string;
  type: "image" | "video" | "music";
  prompt: string | null;
  input_url?: string | null;
  /** Prefer the original fal.ai / provider URL — not an R2/Blob copy. */
  output_url: string;
  status?: "success" | "failed" | "pending" | "processing";
  is_private?: boolean;
  title?: string | null;
  metadata?: Record<string, unknown> | null;
  /** @deprecated Ignored — generated media is not re-uploaded. */
  outputBytes?: Buffer | Uint8Array | null;
  outputContentType?: string;
  outputExt?: string;
  generationId?: string;
  /** @deprecated Ignored for new History rows — no Motio2edit object key. */
  r2ObjectKey?: string | null;
  /** Explicit fal/provider source URL when output_url was rewritten for display. */
  sourceMediaUrl?: string | null;
};

export type PersistGenerationResult = {
  id: string | null;
  retained_as_history: boolean;
  storage_provider: HistoryStorageProvider | null;
  r2_object_key: string | null;
  output_url: string;
  error?: string;
};

function isHttpsUrl(u: string | null | undefined): u is string {
  return !!u && (u.startsWith("https://") || u.startsWith("http://"));
}

/**
 * Insert/upsert a generations row: fal source URL + metadata only.
 * Never uploads generated bytes to R2, Blob, or Supabase Storage.
 * Skips when output URL is missing/empty (no fake History rows).
 */
export async function persistGenerationHistory(
  input: PersistGenerationInput,
): Promise<PersistGenerationResult> {
  const isPrivate = input.is_private !== false;
  const decision = await callShouldRetainAsHistory(
    input.supabaseAdmin,
    input.userId,
    isPrivate,
  );

  // Prefer explicit source (fal) URL when provided; never prefer an R2 signed URL.
  const sourceUrl =
    (isHttpsUrl(input.sourceMediaUrl) ? input.sourceMediaUrl : null) ||
    (isHttpsUrl(input.output_url) ? input.output_url : "");

  if (!sourceUrl) {
    console.warn("[history-persist] skip: empty output_url (no fake History row)");
    return {
      id: null,
      retained_as_history: false,
      storage_provider: null,
      r2_object_key: null,
      output_url: "",
      error: "empty_output_url",
    };
  }

  const genId = input.generationId ?? crypto.randomUUID();

  const meta: Record<string, unknown> = {
    ...(input.metadata ?? {}),
    history_saved: decision.retain,
    source_media_url: sourceUrl || null,
    storage_mode: "provider_link",
  };

  const row: Record<string, unknown> = {
    id: genId,
    user_id: input.userId,
    type: input.type,
    prompt: input.prompt,
    input_url: input.input_url ?? null,
    output_url: sourceUrl,
    status: input.status ?? "success",
    retained_as_history: decision.retain,
    is_private: isPrivate,
    // fal/provider link — not Motio2edit object storage
    storage_provider: decision.retain ? "fal" : null,
    r2_object_key: null,
    thumbnail_key: null,
    deleted_at: null,
    metadata: meta,
  };
  if (input.title != null) row.title = input.title;

  // Idempotent when caller supplies generationId
  const useUpsert = !!input.generationId;
  const write = useUpsert
    ? input.supabaseAdmin.from("generations").upsert(row, { onConflict: "id" }).select("id").maybeSingle()
    : input.supabaseAdmin.from("generations").insert(row).select("id").maybeSingle();

  const { data, error } = await write;

  if (error) {
    if (/column|schema|retained_as_history|storage_provider/i.test(error.message)) {
      const legacy: Record<string, unknown> = {
        user_id: input.userId,
        type: input.type,
        prompt: input.prompt,
        input_url: input.input_url ?? null,
        output_url: sourceUrl,
        status: input.status ?? "success",
        metadata: meta,
      };
      if (input.title != null) legacy.title = input.title;
      if (input.generationId) legacy.id = input.generationId;
      const retry = useUpsert
        ? await input.supabaseAdmin
            .from("generations")
            .upsert(legacy, { onConflict: "id" })
            .select("id")
            .maybeSingle()
        : await input.supabaseAdmin.from("generations").insert(legacy).select("id").maybeSingle();
      return {
        id: (retry.data as { id?: string } | null)?.id ?? null,
        retained_as_history: decision.retain,
        storage_provider: decision.retain ? "fal" : null,
        r2_object_key: null,
        output_url: sourceUrl,
        error: retry.error?.message ?? error.message,
      };
    }
    return {
      id: null,
      retained_as_history: decision.retain,
      storage_provider: decision.retain ? "fal" : null,
      r2_object_key: null,
      output_url: sourceUrl,
      error: error.message,
    };
  }

  console.log(
    "[history-persist] saved id=%s retain=%s provider=fal (link-only) private=%s upsert=%s",
    (data as { id?: string } | null)?.id ?? genId,
    decision.retain,
    isPrivate,
    useUpsert,
  );

  return {
    id: (data as { id?: string } | null)?.id ?? genId,
    retained_as_history: decision.retain,
    storage_provider: decision.retain ? "fal" : null,
    r2_object_key: null,
    output_url: sourceUrl,
  };
}
