/**
 * Central R2 sample catalog — production public URLs only.
 * Domain: https://assets.motio2edit.com
 * Includes media_6 uploads with Standard | Premium | Ultra AI labels.
 */

export const R2_PUBLIC = "https://assets.motio2edit.com" as const;

export type R2Studio = "image" | "video" | "circle" | "auto-edit";
export type R2Feature =
  | "imagine"
  | "circle-remove"
  | "circle-add"
  | "image-generation"
  | "portrait"
  | "enhancement"
  | "video-generation"
  | "auto-edit";

export type HomepageCategory =
  | "samples"
  | "try-now"
  | "trend"
  | "video"
  | "music";

export type SampleQualityTier = "Standard" | "Premium" | "Ultra AI";

export type R2Sample = {
  id: string;
  title: string;
  description: string;
  studio: R2Studio;
  feature: R2Feature;
  homepageCategory?: HomepageCategory;
  tryNowRoute?: string;
  url: string;
  beforeUrl?: string;
  afterUrl?: string;
  intermediateUrl?: string;
  width?: number;
  height?: number;
  aspectRatio: string;
  format: string;
  quality?: string;
  qualityTier?: SampleQualityTier;
  assetId?: string | null;
  fileSizeLabel?: string;
  label?: string;
  durationLabel?: string;
  hasAudio?: boolean;
  sortOrder: number;
  active: boolean;
  filename?: string;
};

const img = (name: string) => `${R2_PUBLIC}/samples/image-studio/${name}`;
const vid = (name: string) => `${R2_PUBLIC}/samples/video/${encodeURIComponent(name)}`;
const cir = (name: string) => `${R2_PUBLIC}/samples/circle-2edit/${name}`;
const media6 = (name: string) =>
  `${R2_PUBLIC}/samples/media_6/${name.split("/").map(encodeURIComponent).join("/")}`;

export const CIRCLE_REMOVE_GIZA = {
  before: cir("file_0000000091d081f585ff54de9335198f.png"),
  mark: cir("file_00000000ab9082089ae984430379abed.png"),
  after: cir("file_000000004e6481faa6caad771de9c84c.png"),
} as const;

export const CIRCLE_ADD_DEER = {
  before: img("IMG-20260903-WA0007.jpg"),
  after: img("IMG-20260903-WA0006.jpg"),
  assetId: "animal_deer" as const,
  width: 784,
  height: 1168,
  aspectRatio: "2:3",
} as const;

/** Image samples — media_6 stills with quality labels. */
export const R2_IMAGE_SAMPLES: R2Sample[] = [
  {
    id: "img-m6-statue-standard",
    title: "Classical Statue",
    description: "Stone statue study in soft light.",
    studio: "image",
    feature: "image-generation",
    homepageCategory: "samples",
    url: media6("Statue_Standard.png"),
    filename: "Statue_Standard.png",
    aspectRatio: "1:1",
    format: "PNG",
    qualityTier: "Standard",
    fileSizeLabel: "1.58 MB",
    label: "Image Studio",
    sortOrder: 400,
    active: true,
  },
  {
    id: "img-m6-violin-standard",
    title: "Violin Study",
    description: "Close instrumental detail of a violin.",
    studio: "image",
    feature: "image-generation",
    homepageCategory: "samples",
    url: media6("violin-standard.png"),
    filename: "violin-standard.png",
    aspectRatio: "1:1",
    format: "PNG",
    qualityTier: "Standard",
    fileSizeLabel: "1.28 MB",
    label: "Image Studio",
    sortOrder: 410,
    active: true,
  },
  {
    id: "img-m6-music-banner",
    title: "Music Studio Banner",
    description: "Brand visual for Music Studio.",
    studio: "image",
    feature: "image-generation",
    homepageCategory: "samples",
    url: media6("Music_banner.png"),
    filename: "Music_banner.png",
    aspectRatio: "1:1",
    format: "PNG",
    qualityTier: "Premium",
    fileSizeLabel: "1.44 MB",
    label: "Music Studio",
    sortOrder: 420,
    active: true,
  },
  {
    id: "img-m6-yau",
    title: "Portrait Light Study",
    description: "Ultra AI portrait sample from media library.",
    studio: "image",
    feature: "portrait",
    homepageCategory: "samples",
    url: media6("yAuGCFx7G649vQi4FxOAs_epd6mEUT.png"),
    filename: "yAuGCFx7G649vQi4FxOAs_epd6mEUT.png",
    aspectRatio: "1:1",
    format: "PNG",
    qualityTier: "Ultra AI",
    fileSizeLabel: "2.42 MB",
    label: "Image Studio",
    sortOrder: 430,
    active: true,
  },
  {
    id: "img-m6-xcgr",
    title: "Editorial Frame",
    description: "Premium still from media library.",
    studio: "image",
    feature: "image-generation",
    homepageCategory: "samples",
    url: media6("xcGrPOM57xd6IeqIQROM4_eAGWfFZE.png"),
    filename: "xcGrPOM57xd6IeqIQROM4_eAGWfFZE.png",
    aspectRatio: "1:1",
    format: "PNG",
    qualityTier: "Premium",
    fileSizeLabel: "1.78 MB",
    label: "Image Studio",
    sortOrder: 440,
    active: true,
  },
  {
    id: "img-m6-vng",
    title: "Scene Still",
    description: "Standard quality still sample.",
    studio: "image",
    feature: "image-generation",
    homepageCategory: "samples",
    url: media6("vNgKSYwBt4mkvdcm-uDDz_9VpVdeTt.png"),
    filename: "vNgKSYwBt4mkvdcm-uDDz_9VpVdeTt.png",
    aspectRatio: "1:1",
    format: "PNG",
    qualityTier: "Standard",
    fileSizeLabel: "1.59 MB",
    label: "Image Studio",
    sortOrder: 450,
    active: true,
  },
  {
    id: "img-m6-qkw",
    title: "Soft Portrait",
    description: "Premium portrait still.",
    studio: "image",
    feature: "portrait",
    homepageCategory: "samples",
    url: media6("qKWRqmccQzbRkqqkcupsd_hWmiOPAu.png"),
    filename: "qKWRqmccQzbRkqqkcupsd_hWmiOPAu.png",
    aspectRatio: "1:1",
    format: "PNG",
    qualityTier: "Premium",
    fileSizeLabel: "2.01 MB",
    label: "Image Studio",
    sortOrder: 460,
    active: true,
  },
  {
    id: "img-m6-qukt",
    title: "Lifestyle Frame",
    description: "Standard lifestyle still.",
    studio: "image",
    feature: "image-generation",
    homepageCategory: "samples",
    url: media6("quKTv9BZOFzcEiJKhwxHj_dEWyAda5.png"),
    filename: "quKTv9BZOFzcEiJKhwxHj_dEWyAda5.png",
    aspectRatio: "1:1",
    format: "PNG",
    qualityTier: "Standard",
    fileSizeLabel: "1.56 MB",
    label: "Image Studio",
    sortOrder: 470,
    active: true,
  },
  {
    id: "img-m6-s5o",
    title: "Product Still",
    description: "Standard product composition.",
    studio: "image",
    feature: "image-generation",
    homepageCategory: "samples",
    url: media6("s5o7V3KUEgWrNrSi5Heux_PVxByRmd.png"),
    filename: "s5o7V3KUEgWrNrSi5Heux_PVxByRmd.png",
    aspectRatio: "1:1",
    format: "PNG",
    qualityTier: "Standard",
    fileSizeLabel: "1.35 MB",
    label: "Image Studio",
    sortOrder: 480,
    active: true,
  },
  {
    id: "img-m6-w1pc",
    title: "Urban Detail",
    description: "Standard urban detail still.",
    studio: "image",
    feature: "image-generation",
    homepageCategory: "samples",
    url: media6("w1pcYswbXbt1l7BC9ikID_5XbprD0B.png"),
    filename: "w1pcYswbXbt1l7BC9ikID_5XbprD0B.png",
    aspectRatio: "3:4",
    format: "PNG",
    qualityTier: "Standard",
    fileSizeLabel: "1.11 MB",
    label: "Image Studio",
    sortOrder: 490,
    active: true,
  },
  {
    id: "img-m6-ejuc",
    title: "Cinematic Still",
    description: "Premium cinematic composition.",
    studio: "image",
    feature: "image-generation",
    homepageCategory: "samples",
    url: media6("eJUc8XRUjc-6nt1t0r7N2_hOYEG2r0.png"),
    filename: "eJUc8XRUjc-6nt1t0r7N2_hOYEG2r0.png",
    aspectRatio: "1:1",
    format: "PNG",
    qualityTier: "Premium",
    fileSizeLabel: "1.91 MB",
    label: "Image Studio",
    sortOrder: 500,
    active: true,
  },
  {
    id: "img-m6-xfp",
    title: "Fashion Frame",
    description: "Premium fashion still.",
    studio: "image",
    feature: "portrait",
    homepageCategory: "samples",
    url: media6("XFpXNpEV1WfXZipkAbpzQ_ROLvh95W.png"),
    filename: "XFpXNpEV1WfXZipkAbpzQ_ROLvh95W.png",
    aspectRatio: "1:1",
    format: "PNG",
    qualityTier: "Premium",
    fileSizeLabel: "1.63 MB",
    label: "Image Studio",
    sortOrder: 510,
    active: true,
  },
  {
    id: "img-m6-yd3",
    title: "Nature Study",
    description: "Standard nature still.",
    studio: "image",
    feature: "image-generation",
    homepageCategory: "samples",
    url: media6("YD3Z4uVofOFstNeBhxSHY_bfPHQ1aq.png"),
    filename: "YD3Z4uVofOFstNeBhxSHY_bfPHQ1aq.png",
    aspectRatio: "1:1",
    format: "PNG",
    qualityTier: "Standard",
    fileSizeLabel: "1.52 MB",
    label: "Image Studio",
    sortOrder: 520,
    active: true,
  },
  {
    id: "img-m6-ybof",
    title: "Abstract Light",
    description: "Premium abstract composition.",
    studio: "image",
    feature: "image-generation",
    homepageCategory: "samples",
    url: media6("-YBofnEairvD-dPdOqPA3_frVvFG7m.png"),
    filename: "-YBofnEairvD-dPdOqPA3_frVvFG7m.png",
    aspectRatio: "1:1",
    format: "PNG",
    qualityTier: "Premium",
    fileSizeLabel: "1.68 MB",
    label: "Image Studio",
    sortOrder: 530,
    active: true,
  },
  {
    id: "img-m6-8j0",
    title: "Editorial Portrait",
    description: "Ultra AI editorial portrait.",
    studio: "image",
    feature: "portrait",
    homepageCategory: "samples",
    url: media6("8-J0_uZQjwu_jmNNrwppi_4ePqbCCj.png"),
    filename: "8-J0_uZQjwu_jmNNrwppi_4ePqbCCj.png",
    aspectRatio: "1:1",
    format: "PNG",
    qualityTier: "Ultra AI",
    fileSizeLabel: "2.09 MB",
    label: "Image Studio",
    sortOrder: 540,
    active: true,
  },
  {
    id: "img-m6-mtz",
    title: "Character Study",
    description: "Premium character still.",
    studio: "image",
    feature: "portrait",
    homepageCategory: "samples",
    url: media6("Mtz710p3tt9lGpUhspvkj_5XXEbO29.png"),
    filename: "Mtz710p3tt9lGpUhspvkj_5XXEbO29.png",
    aspectRatio: "1:1",
    format: "PNG",
    qualityTier: "Premium",
    fileSizeLabel: "1.83 MB",
    label: "Image Studio",
    sortOrder: 550,
    active: true,
  },
  {
    id: "img-m6-rfl",
    title: "Ambient Scene",
    description: "Standard ambient still.",
    studio: "image",
    feature: "image-generation",
    homepageCategory: "samples",
    url: media6("RflS7VE1gG7gXhSI8439N_WNLBGd1t.png"),
    filename: "RflS7VE1gG7gXhSI8439N_WNLBGd1t.png",
    aspectRatio: "1:1",
    format: "PNG",
    qualityTier: "Standard",
    fileSizeLabel: "1.55 MB",
    label: "Image Studio",
    sortOrder: 560,
    active: true,
  },
  {
    id: "img-m6-s2bs",
    title: "Minimal Frame",
    description: "Standard minimal composition.",
    studio: "image",
    feature: "image-generation",
    homepageCategory: "samples",
    url: media6("S2BsFD6zTY2WAUTFn7nXd_bshYNJCt.png"),
    filename: "S2BsFD6zTY2WAUTFn7nXd_bshYNJCt.png",
    aspectRatio: "9:16",
    format: "PNG",
    qualityTier: "Standard",
    fileSizeLabel: "1.01 MB",
    label: "Image Studio",
    sortOrder: 570,
    active: true,
  },
];

/** Video samples — media_6 with Standard | Premium | Ultra AI. No URL duplicates. */
export const R2_VIDEO_SAMPLES: R2Sample[] = [
  {
    id: "vid-m6-tron-racing",
    title: "Tron Racing",
    description: "Neon light-cycle race through a digital grid.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("tron-racing_premium.mp4"),
    filename: "tron-racing_premium.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Premium",
    fileSizeLabel: "19.86 MB",
    hasAudio: true,
    sortOrder: 200,
    active: true,
  },
  {
    id: "vid-m6-ocean-explore",
    title: "Ocean Explore",
    description: "Underwater exploration through coral and open sea.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("ocean-explore_premium.mp4"),
    filename: "ocean-explore_premium.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Premium",
    fileSizeLabel: "17.19 MB",
    hasAudio: true,
    sortOrder: 210,
    active: true,
  },
  {
    id: "vid-m6-truck-journey",
    title: "Truck Journey",
    description: "Long-haul truck on an open highway.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("Truck-journey_standard.mp4"),
    filename: "Truck-journey_standard.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Standard",
    fileSizeLabel: "39.52 MB",
    hasAudio: true,
    sortOrder: 220,
    active: true,
  },
  {
    id: "vid-m6-mom-son-story",
    title: "Mom Love to Son Story",
    description: "Warm mother-and-son story moment.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("Mom-love-to-son-story_standard.mp4"),
    filename: "Mom-love-to-son-story_standard.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Standard",
    fileSizeLabel: "34.4 MB",
    hasAudio: true,
    sortOrder: 230,
    active: true,
  },
  {
    id: "vid-m6-romeo-juliet",
    title: "Romeo & Juliet Love Story",
    description: "Classic romantic retelling in motion.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("RomeoJulietlovestory_Standard.mp4"),
    filename: "RomeoJulietlovestory_Standard.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Standard",
    fileSizeLabel: "8.35 MB",
    hasAudio: true,
    sortOrder: 240,
    active: true,
  },
  {
    id: "vid-m6-water-scarcity",
    title: "World After Water Scarcity",
    description: "Cinematic man in a drought-scarred future.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("world-after-scarcity-of-water-Man_Standard.mp4"),
    filename: "world-after-scarcity-of-water-Man_Standard.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Standard",
    fileSizeLabel: "8.71 MB",
    hasAudio: true,
    sortOrder: 250,
    active: true,
  },
  {
    id: "vid-m6-minimax-q8j",
    title: "Cinematic Motion Clip",
    description: "High-detail MiniMax H3 sample generation.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("q8jY1kF2MpltmH8xxCpE6_minimax-h3.mp4"),
    filename: "q8jY1kF2MpltmH8xxCpE6_minimax-h3.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Ultra AI",
    fileSizeLabel: "20.18 MB",
    hasAudio: true,
    sortOrder: 260,
    active: true,
  },
  {
    id: "vid-m6-minimax-qct",
    title: "Narrative Motion Clip",
    description: "MiniMax H3 story-style sample.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("qCTb0eUmdxhN2ildI9qk5_minimax-h3.mp4"),
    filename: "qCTb0eUmdxhN2ildI9qk5_minimax-h3.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Ultra AI",
    fileSizeLabel: "13.55 MB",
    hasAudio: true,
    sortOrder: 270,
    active: true,
  },
  {
    id: "vid-m6-minimax-xfuy",
    title: "Dynamic Scene Clip",
    description: "MiniMax H3 dynamic scene sample.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("xfUyYfQS2cVkMAgkS2aNA_minimax-h3.mp4"),
    filename: "xfUyYfQS2cVkMAgkS2aNA_minimax-h3.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Premium",
    fileSizeLabel: "22.71 MB",
    hasAudio: true,
    sortOrder: 280,
    active: true,
  },
  {
    id: "vid-m6-output-umw",
    title: "Generated Output Sample",
    description: "Motio2edit video studio output sample.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("uMW_jLw1Z3e_aeNPO9J3g_output.mp4"),
    filename: "uMW_jLw1Z3e_aeNPO9J3g_output.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Standard",
    fileSizeLabel: "11.12 MB",
    hasAudio: true,
    sortOrder: 290,
    active: true,
  },
  {
    id: "vid-m6-music-banner-clip",
    title: "Instrumental Stage Performance",
    description: "Stage performance motion sample.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("Sr58OYuksiNmGUAfA8fwz_minimax-h3.mp4"),
    filename: "Sr58OYuksiNmGUAfA8fwz_minimax-h3.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Premium",
    fileSizeLabel: "19.07 MB",
    hasAudio: true,
    sortOrder: 300,
    active: true,
  },
  {
    id: "vid-m6-music-cello-style",
    title: "Expressive Performance",
    description: "Expressive performance motion sample.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("mu_cw6FFSrZ0lP_JYvyoE_minimax-h3.mp4"),
    filename: "mu_cw6FFSrZ0lP_JYvyoE_minimax-h3.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Premium",
    fileSizeLabel: "19.59 MB",
    hasAudio: true,
    sortOrder: 310,
    active: true,
  },
  {
    id: "vid-m6-minimax-u39",
    title: "Ultra Motion Clip",
    description: "MiniMax H3 ultra-detail sample.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("U39uQkOAvFF3eiTKaSyku_minimax-h3.mp4"),
    filename: "U39uQkOAvFF3eiTKaSyku_minimax-h3.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Ultra AI",
    fileSizeLabel: "24.59 MB",
    hasAudio: true,
    sortOrder: 320,
    active: true,
  },
  {
    id: "vid-m6-minimax-vwm",
    title: "Story Beat Clip",
    description: "MiniMax H3 narrative beat sample.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("VwmDd1l-uNVoAdV6CveHx_minimax-h3.mp4"),
    filename: "VwmDd1l-uNVoAdV6CveHx_minimax-h3.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Ultra AI",
    fileSizeLabel: "21.4 MB",
    hasAudio: true,
    sortOrder: 330,
    active: true,
  },
  {
    id: "vid-m6-minimax-wzh",
    title: "Scene Flow Clip",
    description: "MiniMax H3 scene flow sample.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("WZhH4kaTMmZWvPwIgW-wG_minimax-h3.mp4"),
    filename: "WZhH4kaTMmZWvPwIgW-wG_minimax-h3.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Ultra AI",
    fileSizeLabel: "18.2 MB",
    hasAudio: true,
    sortOrder: 340,
    active: true,
  },
  {
    id: "vid-m6-minimax-xzx",
    title: "Action Beat",
    description: "MiniMax H3 action beat sample.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("XZx_PEegZtVPSOPsNQH0j_minimax-h3.mp4"),
    filename: "XZx_PEegZtVPSOPsNQH0j_minimax-h3.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Ultra AI",
    fileSizeLabel: "16.8 MB",
    hasAudio: true,
    sortOrder: 350,
    active: true,
  },
  {
    id: "vid-m6-minimax-yd2",
    title: "Mood Sequence",
    description: "MiniMax H3 mood sequence sample.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("Yd2PYubItOIE4cODo6yAo_minimax-h3.mp4"),
    filename: "Yd2PYubItOIE4cODo6yAo_minimax-h3.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Ultra AI",
    fileSizeLabel: "15.5 MB",
    hasAudio: true,
    sortOrder: 360,
    active: true,
  },
  {
    id: "vid-m6-minimax-zwav",
    title: "Atmospheric Clip",
    description: "MiniMax H3 atmospheric sample.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("ZwAVMDjzzL-oLWpKGbMyd_minimax-h3.mp4"),
    filename: "ZwAVMDjzzL-oLWpKGbMyd_minimax-h3.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Ultra AI",
    fileSizeLabel: "17.9 MB",
    hasAudio: true,
    sortOrder: 370,
    active: true,
  },
  {
    id: "vid-m6-minimax-nql",
    title: "Character Motion",
    description: "MiniMax H3 character motion sample.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("NqLqUd6edqYWjQxobMHXR_minimax-h3.mp4"),
    filename: "NqLqUd6edqYWjQxobMHXR_minimax-h3.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Ultra AI",
    fileSizeLabel: "14.2 MB",
    hasAudio: true,
    sortOrder: 380,
    active: true,
  },
  {
    id: "vid-m6-minimax-ozf",
    title: "Landscape Motion",
    description: "MiniMax H3 landscape motion sample.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("OZfvk1aXbSI9XpXT98gTo_minimax-h3.mp4"),
    filename: "OZfvk1aXbSI9XpXT98gTo_minimax-h3.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Ultra AI",
    fileSizeLabel: "19.1 MB",
    hasAudio: true,
    sortOrder: 390,
    active: true,
  },
  {
    id: "vid-m6-minimax-qgz",
    title: "Urban Motion",
    description: "MiniMax H3 urban motion sample.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("QGZfGJAmgfbZv2iYwhp5b_minimax-h3.mp4"),
    filename: "QGZfGJAmgfbZv2iYwhp5b_minimax-h3.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Ultra AI",
    fileSizeLabel: "12.8 MB",
    hasAudio: true,
    sortOrder: 400,
    active: true,
  },
  {
    id: "vid-m6-minimax-q3u",
    title: "Close-up Motion",
    description: "MiniMax H3 close-up motion sample.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("q3UK7WOyvfbLmnj_5TVH0_minimax-h3.mp4"),
    filename: "q3UK7WOyvfbLmnj_5TVH0_minimax-h3.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Ultra AI",
    fileSizeLabel: "11.5 MB",
    hasAudio: true,
    sortOrder: 410,
    active: true,
  },
  {
    id: "vid-m6-minimax-yxh",
    title: "Wide Scene Motion",
    description: "MiniMax H3 wide scene sample.",
    studio: "video",
    feature: "video-generation",
    homepageCategory: "video",
    url: media6("yXHb1coY9Gz787BmPb2XA_minimax-h3.mp4"),
    filename: "yXHb1coY9Gz787BmPb2XA_minimax-h3.mp4",
    aspectRatio: "16:9",
    format: "MP4",
    qualityTier: "Ultra AI",
    fileSizeLabel: "13.9 MB",
    hasAudio: true,
    sortOrder: 420,
    active: true,
  },
];

export const HOMEPAGE_WATCH_DEMO = {
  url: media6("tron-racing_premium.mp4"),
  poster: media6("Music_banner.png"),
  title: "Tron Racing",
} as const;

function dedupeByUrl(samples: R2Sample[]): R2Sample[] {
  const seen = new Set<string>();
  return samples.filter((s) => {
    if (!s.active || !s.url || seen.has(s.url)) return false;
    seen.add(s.url);
    return true;
  });
}

export function getActiveR2ImageSamples(): R2Sample[] {
  return dedupeByUrl(R2_IMAGE_SAMPLES).sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getActiveR2VideoSamples(): R2Sample[] {
  return dedupeByUrl(R2_VIDEO_SAMPLES).sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getImagineOnlySamples(): R2Sample[] {
  return getActiveR2ImageSamples().filter(
    (s) => s.studio === "image" || s.studio === "circle",
  );
}

export function getMusicVideoSamples(): R2Sample[] {
  return getActiveR2VideoSamples().filter((s) => s.homepageCategory === "music");
}

export function getVideoOnlySamples(): R2Sample[] {
  return getActiveR2VideoSamples().filter((s) => s.homepageCategory !== "music");
}

/** All discoverable homepage samples (images + videos), deduped by URL. */
export function getAllDiscoverSamples(): R2Sample[] {
  return dedupeByUrl([...R2_IMAGE_SAMPLES, ...R2_VIDEO_SAMPLES]).sort(
    (a, b) => a.sortOrder - b.sortOrder,
  );
}

export function getR2SampleById(id: string): R2Sample | null {
  return (
    R2_IMAGE_SAMPLES.find((s) => s.id === id) ??
    R2_VIDEO_SAMPLES.find((s) => s.id === id) ??
    null
  );
}
