/**
 * Motio2edit 100-filter catalog — original short-name recipes.
 * Common 40 (free) · AI+ 35 · Premium 25
 * Distinct looks only. No proprietary preset clones.
 * Photo-inspired AI+/Premium: Rain Neon, Open Road, City Reflect, Night Soft, Garden Soft, Dew Bloom, Side Glow, Frost Clean, Metal Luxe, Anime Soft.
 */
import { FilterDefinition } from './filter-types';
import { createAttribution, createUnlockMetadata } from '../shared/metadata';

const IR = { min: 0, max: 100, default: 85 } as const;

function f(
  id: string,
  name: string,
  category: FilterDefinition['category'],
  desc: string,
  profile: FilterDefinition['processingProfile'],
  opts: { free?: boolean; tier?: 'ai+' | 'pro' | 'premium'; animated?: boolean; cost?: number } = {},
): FilterDefinition {
  const isFree = !!opts.free;
  return {
    id,
    name,
    category,
    description: desc,
    visualDescription: desc,
    icon: `icon-${id}`,
    previewKey: `preview-${id}`,
    processingProfile: profile,
    intensityRange: IR,
    supportsPreview: true as const,
    supportsFullResolution: true as const,
    supportsCamera: false as const,
    developerNotes: '',
    attribution: createAttribution(),
    unlock: createUnlockMetadata(isFree ? 0 : opts.cost ?? 12, isFree),
    ...(isFree ? {} : { tier: opts.tier ?? 'premium' }),
    ...(opts.animated ? { animatedThumb: true } : {}),
  };
}

export const FILTERS_CURATED: FilterDefinition[] = [
  f('filter-001', 'Vivid', 'Natural',
    'Everyday punchy color with clean midtones for social and lifestyle shots.',
    { contrast: 22, saturation: 24, vibrance: 20, clarity: 12, shadows: 10 }, { free: true }),
  f('filter-002', 'Warm', 'Portrait',
    'Gentle warm portrait grade that keeps natural skin texture.',
    { temperature: 14, softBlur: 10, shadows: 12, saturation: 6, contrast: 12, clarity: -4 }, { free: true }),
  f('filter-003', 'Glow', 'Soft',
    'Soft luminous highlights with airy contrast for dreamy portraits.',
    { softBlur: 18, bloom: 16, clarity: -10, fade: 8, contrast: 10, temperature: 6 }, { free: true }),
  f('filter-004', 'Clear', 'Natural',
    'Balanced daylight grade with clear midtones and mild clarity.',
    { contrast: 16, vibrance: 14, clarity: 10, temperature: 4, sharpening: 8 }, { free: true }),
  f('filter-005', 'Fresh', 'Natural',
    'Open outdoor lift with slightly cooler sky-friendly tones.',
    { exposure: 6, shadows: 18, contrast: 14, vibrance: 14, temperature: -2 }, { free: true }),
  f('filter-006', 'Golden', 'Portrait',
    'Warm golden skin midtones without heavy smoothing.',
    { temperature: 18, tint: 4, softBlur: 8, shadows: 10, saturation: 8, contrast: 12 }, { free: true }),
  f('filter-007', 'Urban', 'Street',
    'Crisp street grade with urban contrast and mild vignette.',
    { contrast: 24, clarity: 16, sharpening: 12, saturation: 8, vignette: 12 }, { free: true }),
  f('filter-008', 'Street', 'Street',
    'Cooler street grit with stronger midtone contrast.',
    { temperature: -10, contrast: 26, clarity: 14, saturation: 6, vignette: 14 }, { free: true }),
  f('filter-009', 'Matte', 'Soft',
    'Lifted blacks and matte soft finish for modern lifestyle looks.',
    { fade: 20, contrast: 10, saturation: -6, softBlur: 6, vignette: 8 }, { free: true }),
  f('filter-010', 'B/W', 'Black & White',
    'True neutral grayscale with balanced tones for portraits, street, and everyday photos.',
    { monochrome: true, contrast: 18, clarity: 10, shadows: 6, highlights: -4, grain: 3, vignette: 4 }, { free: true }),
  f('filter-011', 'Deep B/W', 'Black & White',
    'Dramatic monochrome with deeper blacks and stronger tonal separation while preserving detail.',
    { monochrome: true, contrast: 38, shadows: -16, highlights: -6, clarity: 14, vignette: 16, grain: 5 }, { free: true }),
  f('filter-012', 'Silver', 'Black & White',
    'Soft silver gelatin feel with visible grain.',
    { monochrome: true, contrast: 16, grain: 22, fade: 10, vignette: 12 }, { free: true }),
  f('filter-013', 'Vintage', 'Vintage',
    'Warm analog 70s fade with muted color and soft grain.',
    { temperature: 24, fade: 22, grain: 16, saturation: -8, contrast: 12, vignette: 14 }, { free: true }),
  f('filter-014', '90s', 'Vintage',
    'Cooler 90s nostalgic cast with firmer contrast and grain.',
    { temperature: -4, fade: 16, grain: 18, contrast: 18, saturation: -6, vignette: 12 }, { free: true }),
  f('filter-015', '80s', 'Retro',
    'Soft retro wash with warm midtones and gentle blur.',
    { temperature: 16, fade: 18, softBlur: 10, grain: 12, saturation: 8 }, { free: true }),
  f('filter-016', 'Instant', 'Retro',
    'Instant-camera warmth, soft edges, and vignette.',
    { temperature: 16, fade: 18, grain: 14, vignette: 26, softBlur: 8, saturation: 6 }, { free: true }),
  f('filter-017', 'Pastel', 'Soft',
    'Muted pastel colors with soft bloom for gentle moods.',
    { softBlur: 14, fade: 14, saturation: -10, temperature: 6, bloom: 10 }, { free: true }),
  f('filter-018', 'Rose', 'Portrait',
    'Subtle rose-tinted glow for flattering portrait light.',
    { temperature: 10, tint: 8, bloom: 12, softBlur: 10, saturation: 6 }, { free: true }),
  f('filter-019', 'Sunset', 'Sunset',
    'Soft natural sunset warmth with gentle red-gold light and restrained highlights.',
    { temperature: 22, tint: 6, saturation: 10, highlights: -12, shadows: 10, fade: 4 }, { free: true }),
  f('filter-020', 'Morning', 'Natural',
    'Soft morning lift with gentle warmth.',
    { exposure: 6, temperature: 8, shadows: 14, softBlur: 6, contrast: 12 }, { free: true }),
  f('filter-021', 'Cloudy', 'Film',
    'Soft cloudy film grade with mild desaturation.',
    { fade: 16, temperature: -4, grain: 10, contrast: 12, saturation: -8 }, { free: true }),
  f('filter-022', 'Doc', 'Street',
    'Documentary street fade with restrained color.',
    { fade: 16, contrast: 14, clarity: 10, saturation: -10, grain: 8 }, { free: true }),
  f('filter-023', 'Night', 'Night',
    'Night scene with lifted shadows and cool cast.',
    { temperature: -12, shadows: 20, contrast: 16, grain: 8, vignette: 16 }, { free: true }),
  f('filter-024', 'Blue', 'Cool',
    'Cool blue-hour atmosphere for dusk and city lights.',
    { temperature: -18, tint: -4, shadows: 12, contrast: 14, vignette: 14 }, { free: true }),
  f('filter-025', 'Café', 'Warm',
    'Interior café warmth with soft shadows.',
    { temperature: 20, tint: 4, shadows: 8, saturation: 10, vignette: 10 }, { free: true }),
  f('filter-026', 'Food', 'Food',
    'Rich food color and contrast for plates and product shots.',
    { saturation: 24, vibrance: 18, contrast: 20, clarity: 12, temperature: 6 }, { free: true }),
  f('filter-027', 'Travel', 'Travel',
    'Bright travel-ready grade for outdoor and landmarks.',
    { exposure: 6, vibrance: 16, contrast: 14, saturation: 12, clarity: 8 }, { free: true }),
  f('filter-028', 'Portrait', 'Portrait',
    'Natural soft portrait with gentle contrast and skin-friendly midtones.',
    { softBlur: 10, shadows: 14, temperature: 6, contrast: 10, clarity: -8, saturation: 4, highlights: -4 }, { free: true }),
  f('filter-029', 'Soft Light', 'Portrait',
    'Luminous portrait finish with refined warm highlights and polished glow.',
    { bloom: 16, softBlur: 6, temperature: 10, contrast: 14, shadows: 10, saturation: 6, highlights: -6, clarity: 2 }, { free: true }),
  f('filter-030', 'Crisp', 'Professional',
    'Crisp detail and mild contrast for product and architecture.',
    { clarity: 20, sharpening: 14, contrast: 18, vibrance: 10, shadows: 4 }, { free: true }),
  f('filter-031', 'Gentle', 'Natural',
    'Gentle contrast without harsh edges for everyday photos.',
    { contrast: 12, shadows: 8, highlights: -6, vibrance: 8, clarity: 6 }, { free: true }),
  f('filter-032', 'Rich', 'Natural',
    'Fuller saturation with controlled vibrance for colorful scenes.',
    { saturation: 26, vibrance: 16, contrast: 16, clarity: 8 }, { free: true }),
  f('filter-033', 'Muted', 'Soft',
    'Desaturated muted palette for calm editorial tones.',
    { saturation: -16, fade: 12, contrast: 10, temperature: 2, vignette: 8 }, { free: true }),
  f('filter-034', 'Film', 'Film',
    'Classic film fade with soft grain.',
    { fade: 22, grain: 12, contrast: 12, temperature: 6, vignette: 12 }, { free: true }),
  f('filter-035', 'Analog', 'Film',
    'Analog film touch with grain and mild warmth.',
    { grain: 20, fade: 12, contrast: 14, temperature: 8, vignette: 10, saturation: -4 }, { free: true }),
  f('filter-036', 'Ocean', 'Cool',
    'Cool oceanic cyan-blue grade for water and coastal scenes.',
    { temperature: -14, tint: -6, saturation: 8, contrast: 14, shadows: 10 }, { free: true }),
  f('filter-037', 'Arctic', 'Cool',
    'Cold arctic clarity with crisp blues and firm contrast.',
    { temperature: -20, contrast: 20, clarity: 14, saturation: -4, vignette: 10 }, { free: true }),
  f('filter-038', 'Orange', 'Warm',
    'Warm orange-golden film character with soft density and analog midtones.',
    { temperature: 26, tint: 8, saturation: 8, contrast: 12, fade: 10, grain: 10, vignette: 12 }, { free: true }),
  f('filter-039', 'Cyan', 'Cool',
    'Soft cyan cast with lifted shadows for modern cool looks.',
    { temperature: -12, tint: -8, shadows: 14, contrast: 12, saturation: 6 }, { free: true }),
  f('filter-040', 'Warm Pop', 'Natural',
    'Warm everyday pop with friendly skin and social-ready color.',
    { temperature: 12, saturation: 18, vibrance: 16, contrast: 16, shadows: 8 }, { free: true }),
  f('filter-041', 'Ember', 'Cinematic',
    'Deep red-orange cinematic ember with rich shadows and film grain.',
    { temperature: 20, tint: 10, contrast: 28, vignette: 24, shadows: -4, grain: 12, saturation: 12, highlights: -8 }, { tier: 'ai+', cost: 8 }),
  f('filter-042', 'Cinema', 'Cinematic',
    'Teal shadows with warmer highlights for classic cinema color split.',
    { temperature: -10, tint: -6, contrast: 24, vignette: 20, shadows: 8, splitToning: { shadowsHue: 190, shadowsSaturation: 28, highlightsHue: 35, highlightsSaturation: 18, balance: -8 } }, { tier: 'ai+', cost: 8 }),
  f('filter-043', 'Midnight', 'Cinematic',
    'Cool midnight frame with strong vignette and night grain.',
    { temperature: -16, contrast: 28, vignette: 28, grain: 12, shadows: 10 }, { tier: 'ai+', cost: 8 }),
  f('filter-044', 'Gold Hour', 'Cinematic',
    'Golden cinematic warmth with controlled highlights.',
    { temperature: 20, contrast: 22, vignette: 18, saturation: 12, highlights: -8 }, { tier: 'ai+', cost: 8 }),
  f('filter-045', 'Moody', 'Moody',
    'Desaturated silver mood with firm contrast and soft fade.',
    { saturation: -22, contrast: 22, fade: 12, vignette: 20, grain: 8 }, { tier: 'ai+', cost: 8 }),
  f('filter-046', 'Noir', 'Black & White',
    'Hard noir blacks with high contrast and deep vignette.',
    { monochrome: true, contrast: 40, shadows: -16, vignette: 30, grain: 12, clarity: 10 }, { tier: 'ai+', cost: 8 }),
  f('filter-047', 'Velvet', 'Moody',
    'Velvet soft shadows with gentle cool cast.',
    { shadows: 16, softBlur: 12, contrast: 14, fade: 8, vignette: 16, temperature: -4 }, { tier: 'ai+', cost: 8 }),
  f('filter-048', 'Editorial', 'Fashion',
    'Editorial skin-friendly contrast for fashion stills.',
    { contrast: 20, clarity: 6, temperature: 4, softBlur: 6, saturation: 6, vignette: 10 }, { tier: 'ai+', cost: 8 }),
  f('filter-049', 'Runway', 'Fashion',
    'High fashion contrast and clarity for runway energy.',
    { contrast: 30, clarity: 14, sharpening: 10, saturation: 8, vignette: 14 }, { tier: 'ai+', cost: 8 }),
  f('filter-050', 'Rain Neon', 'Neon',
    'Wet-street neon night with warm lamps, cool reflections, and rain atmosphere.',
    { style: 'neon', temperature: -6, contrast: 26, saturation: 18, bloom: 14, vignette: 20, grain: 8, shadows: 8, splitToning: { shadowsHue: 210, shadowsSaturation: 22, highlightsHue: 35, highlightsSaturation: 16, balance: -6 } }, { tier: 'ai+', cost: 8, animated: true }),
  f('filter-051', 'Neon Blue', 'Neon',
    'Electric neon blue-cyan push for night city color.',
    { style: 'neon', saturation: 30, contrast: 24, bloom: 18, temperature: -12, vignette: 16 }, { tier: 'ai+', cost: 8, animated: true }),
  f('filter-052', 'Neon Red', 'Neon',
    'Intense electric red-magenta night glow with strong bloom.',
    { style: 'neon', saturation: 34, bloom: 22, contrast: 22, temperature: 8, vignette: 20 }, { tier: 'ai+', cost: 8, animated: true }),
  f('filter-053', 'Dream', 'Film',
    'Dreamy film with soft hilation and warm grain.',
    { softBlur: 14, bloom: 16, fade: 12, grain: 10, temperature: 8, contrast: 12 }, { tier: 'ai+', cost: 8 }),
  f('filter-054', 'Dust', 'Film',
    'Heavy dusty grain and faded film density.',
    { grain: 28, fade: 16, contrast: 14, temperature: 6, vignette: 14, saturation: -6 }, { tier: 'ai+', cost: 8 }),
  f('filter-055', 'Crimson', 'Warm',
    'Dramatic red-forward heat with intense warm midtones and controlled highlights.',
    { temperature: 32, tint: 14, saturation: 16, contrast: 22, highlights: -12, vignette: 16, shadows: -4 }, { tier: 'ai+', cost: 8 }),
  f('filter-056', 'Grain', 'Film',
    'Strong film grain texture with balanced contrast.',
    { grain: 30, contrast: 16, fade: 10, temperature: 4, vignette: 12 }, { tier: 'ai+', cost: 8 }),
  f('filter-057', 'Fairytale', 'Soft',
    'Dreamy fairytale grade with soft luminous highlights, gentle pastel harmony, and delicate glow — ideal for portraits, flowers, family, and romantic scenes.',
    { softBlur: 16, bloom: 20, fade: 12, temperature: 10, tint: 4, saturation: -4, vibrance: 12, contrast: 8, clarity: -10, shadows: 12, splitToning: { shadowsHue: 280, shadowsSaturation: 14, highlightsHue: 42, highlightsSaturation: 16, balance: 4 } }, { tier: 'ai+', cost: 8 }),
  f('filter-058', 'Drama Face', 'Portrait',
    'Dramatic portrait contrast with controlled shadows.',
    { contrast: 26, shadows: -6, vignette: 20, clarity: 10, temperature: 4, saturation: 6 }, { tier: 'ai+', cost: 8 }),
  f('filter-059', 'Window', 'Cinematic',
    'Window-light cinema with soft shadow lift.',
    { contrast: 20, shadows: 14, temperature: 6, vignette: 16, softBlur: 4, highlights: -8 }, { tier: 'ai+', cost: 8 }),
  f('filter-060', 'Golden Hour', 'Sunset',
    'Pro golden-hour warmth with rich separation.',
    { temperature: 28, tint: 6, saturation: 14, highlights: -10, shadows: 10, vignette: 12 }, { tier: 'ai+', cost: 8 }),
  f('filter-061', 'Frost Clean', 'Cool',
    'Clean arctic frost grade with crisp whites, cool air, and soft shadow lift.',
    { temperature: -18, tint: -4, contrast: 20, clarity: 12, shadows: 12, saturation: -6, vignette: 8 }, { tier: 'ai+', cost: 8 }),
  f('filter-062', 'Open Road', 'Landscape',
    'Wide open-road golden-hour grade with deep sky contrast and warm path tones.',
    { temperature: 16, contrast: 26, clarity: 14, vignette: 18, shadows: -6, saturation: 8, highlights: -8 }, { tier: 'ai+', cost: 8 }),
  f('filter-063', 'Urban Drama', 'Dramatic',
    'Urban dramatic contrast for architecture and streets.',
    { contrast: 34, clarity: 16, vignette: 24, shadows: -8, saturation: 6 }, { tier: 'ai+', cost: 8 }),
  f('filter-064', 'City Reflect', 'Night',
    'Wet-city night reflections with punchy lights and cool-warm street balance.',
    { contrast: 28, saturation: 14, vibrance: 12, temperature: -4, vignette: 16, shadows: 6, bloom: 10, splitToning: { shadowsHue: 220, shadowsSaturation: 18, highlightsHue: 40, highlightsSaturation: 20, balance: 0 } }, { tier: 'ai+', cost: 8 }),
  f('filter-065', 'Music Video', 'Cinematic',
    'Punchy music-video grade with vivid contrast.',
    { contrast: 28, saturation: 20, vibrance: 16, vignette: 18, clarity: 12 }, { tier: 'ai+', cost: 8 }),
  f('filter-066', 'Night Soft', 'Portrait',
    'Soft night portrait with warm skin, gentle bloom, and city-light bokeh feel.',
    { temperature: 8, softBlur: 10, bloom: 14, shadows: 14, contrast: 12, saturation: 6, vignette: 12, highlights: -6 }, { tier: 'ai+', cost: 8 }),
  f('filter-067', 'Garden Soft', 'Portrait',
    'Soft outdoor portrait grade with golden light, airy skin, and gentle floral warmth.',
    { temperature: 14, softBlur: 12, bloom: 12, fade: 8, contrast: 10, clarity: -6, saturation: 6, shadows: 10 }, { tier: 'ai+', cost: 8 }),
  f('filter-068', 'Side Glow', 'Portrait',
    'Golden side-light portrait with rim warmth and natural skin texture.',
    { temperature: 18, contrast: 18, shadows: -4, highlights: -8, softBlur: 4, clarity: 6, saturation: 6, vignette: 14 }, { tier: 'ai+', cost: 8 }),
  f('filter-069', 'Rich Neg', 'Film',
    'Dense negative-inspired color and contrast.',
    { contrast: 26, saturation: 14, shadows: -4, grain: 10, vignette: 16, temperature: 4 }, { tier: 'ai+', cost: 8 }),
  f('filter-070', 'Matte Cinema', 'Cinematic',
    'Matte cinema blacks with restrained color.',
    { fade: 20, contrast: 18, vignette: 18, saturation: -10, grain: 6 }, { tier: 'ai+', cost: 8 }),
  f('filter-071', 'Hard Film', 'Film',
    'High-contrast film punch with grain.',
    { contrast: 34, grain: 14, vignette: 18, shadows: -10, saturation: 8 }, { tier: 'ai+', cost: 8 }),
  f('filter-072', 'Dew Bloom', 'Soft',
    'Dewy flower-light soft grade with luminous highlights and gentle pastel glow.',
    { softBlur: 12, bloom: 20, fade: 10, temperature: 10, tint: 4, saturation: -4, vibrance: 12, contrast: 8, clarity: -10, shadows: 8 }, { tier: 'ai+', cost: 8 }),
  f('filter-073', 'Peacock', 'Art',
    'Vivid multi-color peacock look: rich cyan, emerald, violet, magenta and golden separation with strong tonal depth — inspired by saturated urban color at golden hour.',
    { saturation: 30, vibrance: 34, contrast: 24, temperature: -6, tint: 14, splitToning: { shadowsHue: 195, shadowsSaturation: 52, highlightsHue: 40, highlightsSaturation: 36, balance: -12 }, clarity: 12, shadows: 6, bloom: 8 }, { tier: 'ai+', cost: 8, animated: true }),
  f('filter-074', 'Color Burst', 'Art',
    'Explosive controlled color energy for fashion and nightlife.',
    { saturation: 34, vibrance: 28, contrast: 22, clarity: 10, vignette: 12 }, { tier: 'ai+', cost: 8, animated: true }),
  f('filter-075', 'Prism', 'Art',
    'Prism-like color shifts with cool shadows and warm highlights.',
    { contrast: 18, saturation: 22, vibrance: 20, splitToning: { shadowsHue: 260, shadowsSaturation: 30, highlightsHue: 50, highlightsSaturation: 22, balance: 0 }, clarity: 8 }, { tier: 'ai+', cost: 8 }),
  f('filter-076', 'Large Format', 'Professional',
    'Large-format-inspired clarity, depth, and refined dynamic range.',
    { clarity: 26, contrast: 24, sharpening: 14, vignette: 16, shadows: 6, vibrance: 10 }, { tier: 'premium', cost: 12 }),
  f('filter-077', 'Ultra Cinema', 'Cinematic',
    'Ultra cinematic contrast frame with deep vignette.',
    { contrast: 32, vignette: 30, grain: 10, shadows: -6, temperature: -2, saturation: 8 }, { tier: 'premium', cost: 12 }),
  f('filter-078', 'Ultra Detail', 'Professional',
    'Hyper-detail microclarity aesthetic for architecture and product.',
    { clarity: 32, sharpening: 20, contrast: 20, microcontrast: 16, vibrance: 8 }, { tier: 'premium', cost: 12 }),
  f('filter-079', 'Epic Frame', 'Cinematic',
    'IMAX-inspired epic contrast and scale without resolution claims.',
    { contrast: 30, vignette: 26, clarity: 18, shadows: -4, saturation: 10, grain: 6 }, { tier: 'premium', cost: 12 }),
  f('filter-080', 'Grand Cinema', 'Cinematic',
    'Grand cinematic scale with warm vibrance and vignette.',
    { contrast: 28, vignette: 26, temperature: 4, grain: 8, shadows: 6, vibrance: 12 }, { tier: 'premium', cost: 12 }),
  f('filter-081', 'Wide Drama', 'Dramatic',
    'Widescreen dramatic punch for landscapes and streets.',
    { contrast: 34, vignette: 28, clarity: 14, shadows: -8, saturation: 8 }, { tier: 'premium', cost: 12 }),
  f('filter-082', 'Deep Range', 'Professional',
    'Extended dynamic range with controlled highlights and lifted shadows.',
    { dynamicRange: 28, contrast: 20, clarity: 12, shadows: 10, highlights: -10, vignette: 12 }, { tier: 'premium', cost: 12 }),
  f('filter-083', 'Gold', 'Cinematic',
    'Rich gold cinematic warmth with refined contrast.',
    { temperature: 22, contrast: 26, vignette: 22, saturation: 12, grain: 6 }, { tier: 'premium', cost: 12 }),
  f('filter-084', 'Cinema Pro', 'Cinematic',
    'Pro cinema grade with teal-warm split and firm vignette.',
    { contrast: 28, vignette: 24, splitToning: { shadowsHue: 185, shadowsSaturation: 30, highlightsHue: 38, highlightsSaturation: 18, balance: -10 }, grain: 8, saturation: 6 }, { tier: 'premium', cost: 12 }),
  f('filter-085', 'Detail', 'Professional',
    'Maximum useful detail and microcontrast for product and architecture.',
    { clarity: 30, sharpening: 18, microcontrast: 16, contrast: 18, vibrance: 8 }, { tier: 'premium', cost: 12 }),
  f('filter-086', 'Epic', 'Cinematic',
    'Epic scale contrast and vignette for dramatic frames.',
    { contrast: 34, vignette: 28, clarity: 16, shadows: -8, saturation: 8, grain: 6 }, { tier: 'premium', cost: 12 }),
  f('filter-087', 'Master', 'Cinematic',
    'Master cinematic polish with balanced color and depth.',
    { contrast: 26, vignette: 22, clarity: 14, temperature: 2, saturation: 8, grain: 6 }, { tier: 'premium', cost: 12 }),
  f('filter-088', 'Metal Luxe', 'Professional',
    'Luxury product polish with micro-detail, controlled contrast, and refined metal tones.',
    { clarity: 28, sharpening: 18, contrast: 22, microcontrast: 14, vignette: 12, saturation: 4, shadows: 4 }, { tier: 'premium', cost: 12 }),
  f('filter-089', 'Ocean Pro', 'Landscape',
    'Oceanic cinematic cool with deep range.',
    { temperature: -12, tint: -6, contrast: 22, shadows: 12, vignette: 14, vibrance: 10 }, { tier: 'premium', cost: 12 }),
  f('filter-090', 'Mountain', 'Landscape',
    'Mountain grandeur with crisp clarity and cool air.',
    { clarity: 24, contrast: 24, temperature: -4, vignette: 14, shadows: 8, vibrance: 10 }, { tier: 'premium', cost: 12 }),
  f('filter-091', 'Black Glass', 'Black & White',
    'Deep black-glass mono with crushed blacks.',
    { monochrome: true, contrast: 42, shadows: -18, vignette: 32, clarity: 16, grain: 8 }, { tier: 'premium', cost: 12 }),
  f('filter-092', 'Platinum', 'Black & White',
    'Soft platinum mono with gentle fade.',
    { monochrome: true, contrast: 18, fade: 12, grain: 10, vignette: 12, softBlur: 4 }, { tier: 'premium', cost: 12 }),
  f('filter-093', 'Luxe', 'Cinematic',
    'Velvet soft drama cinema grade.',
    { softBlur: 12, contrast: 22, vignette: 22, fade: 8, temperature: 4, saturation: 6 }, { tier: 'premium', cost: 12 }),
  f('filter-094', 'Director', 'Cinematic',
    'Director-style cool cinematic grade.',
    { contrast: 26, vignette: 24, temperature: -4, tint: -4, grain: 8, saturation: 4, shadows: 6 }, { tier: 'premium', cost: 12 }),
  f('filter-095', 'Anime Soft', 'Comic',
    'Soft anime-inspired grade with luminous skin, pastel bloom, and clean color fields.',
    { softBlur: 10, bloom: 16, saturation: 18, vibrance: 14, contrast: 14, temperature: 6, fade: 6, clarity: -4 }, { tier: 'premium', cost: 12 }),
  f('filter-096', 'Contrast', 'Dramatic',
    'Maximum controlled contrast for graphic drama.',
    { contrast: 40, shadows: -14, vignette: 26, clarity: 14, saturation: 6 }, { tier: 'premium', cost: 12 }),
  f('filter-097', 'Pure', 'Natural',
    'Ultra-clean natural polish for premium everyday shots.',
    { contrast: 16, clarity: 14, vibrance: 12, sharpening: 10, shadows: 6, temperature: 2 }, { tier: 'premium', cost: 12 }),
  f('filter-098', 'Studio', 'Portrait',
    'Hyper-real portrait detail with subtle polish.',
    { clarity: 20, sharpening: 14, contrast: 18, softBlur: 2, temperature: 4, saturation: 6, vignette: 10 }, { tier: 'premium', cost: 12 }),
  f('filter-099', 'Comic', 'Comic',
    'Illustrated comic treatment with flat graphic colors and clear ink-line contours.',
    { style: 'comic', contrast: 12, saturation: 10, vibrance: 8 }, { tier: 'premium', cost: 12 }),
  f('filter-100', 'Sketch', 'Sketch',
    'Pencil drawing look with visible line structure, paper tone, and artistic shading.',
    { style: 'sketch' }, { tier: 'premium', cost: 12 }),
];
