/**
 * Motio2edit 100-filter catalog — original recipes.
 * Common 40 (all free) · AI+ 35 · Premium 25
 * On-device pixel grades only. No proprietary preset clones.
 */
import { FilterDefinition } from './filter-types';
import { createAttribution, createUnlockMetadata } from '../shared/metadata';

const IR = { min: 0, max: 100, default: 85 } as const;

function f(
  id: string,
  name: string,
  category: FilterDefinition['category'],
  desc: string,
  profile: FilterDefinition['processingProfile'],
  opts: { free?: boolean; tier?: 'ai+' | 'pro' | 'premium'; animated?: boolean; cost?: number } = {},
): FilterDefinition {
  const isFree = !!opts.free;
  return {
    id, name, category,
    description: `${name} — ${desc}`,
    visualDescription: `${name} visual character.`,
    icon: `icon-${id}`,
    previewKey: `preview-${id}`,
    processingProfile: profile,
    intensityRange: IR,
    supportsPreview: true as const,
    supportsFullResolution: true as const,
    supportsCamera: false as const,
    developerNotes: '',
    attribution: createAttribution(),
    unlock: createUnlockMetadata(isFree ? 0 : opts.cost ?? 12, isFree),
    ...(isFree ? {} : { tier: opts.tier ?? 'premium' }),
    ...(opts.animated ? { animatedThumb: true } : {}),
  };
}

export const FILTERS_CURATED: FilterDefinition[] = [
  f('filter-001', 'Vivid Lift', 'Natural', 'Punchy everyday color lift with clean midtones.',
    { contrast: 22, saturation: 24, vibrance: 20, clarity: 12, shadows: 10 }, { free: true }),
  f('filter-002', 'Warm Portrait', 'Portrait', 'Warm skin-friendly portrait with soft lift.',
    { temperature: 16, softBlur: 12, shadows: 14, saturation: 8, contrast: 12 }, { free: true }),
  f('filter-003', 'Soft Air', 'Soft', 'Airy soft finish with gentle bloom.',
    { softBlur: 22, bloom: 16, clarity: -10, fade: 10, contrast: 8 }, { free: true }),
  f('filter-004', 'Clean Natural', 'Natural', 'Balanced natural daylight grade.',
    { contrast: 16, vibrance: 14, clarity: 10, temperature: 4, sharpening: 8 }, { free: true }),
  f('filter-005', 'Everyday Pop', 'Natural', 'Social-ready everyday pop.',
    { saturation: 20, vibrance: 22, contrast: 18, clarity: 14, shadows: 8 }, { free: true }),
  f('filter-006', 'Golden Skin', 'Portrait', 'Golden skin tones with soft contrast.',
    { temperature: 20, tint: 4, softBlur: 10, shadows: 12, saturation: 10 }, { free: true }),
  f('filter-007', 'Fresh Daylight', 'Natural', 'Fresh open daylight with lifted shadows.',
    { exposure: 8, shadows: 20, contrast: 14, vibrance: 16, temperature: 6 }, { free: true }),
  f('filter-008', 'Urban Clean', 'Street', 'Clean urban grade with crisp detail.',
    { contrast: 24, clarity: 18, sharpening: 14, saturation: 10, vignette: 12 }, { free: true }),
  f('filter-009', 'Cool Street', 'Street', 'Cool street tones with grit.',
    { temperature: -10, contrast: 26, clarity: 16, saturation: 8, vignette: 14 }, { free: true }),
  f('filter-010', 'Soft Matte', 'Soft', 'Matte soft look with lifted blacks.',
    { fade: 22, contrast: 10, saturation: -6, softBlur: 8, vignette: 10 }, { free: true }),
  f('filter-011', 'Faded Memory', 'Vintage', 'Faded memory with soft grain.',
    { fade: 28, grain: 18, temperature: 10, saturation: -12, contrast: 12 }, { free: true }),
  f('filter-012', 'Gentle Sepia', 'Vintage', 'Gentle sepia wash.',
    { sepia: 45, fade: 16, grain: 14, contrast: 14, vignette: 18 }, { free: true }),
  f('filter-013', 'Classic Mono', 'Black & White', 'Classic clean monochrome.',
    { monochrome: true, contrast: 22, clarity: 10, grain: 6, vignette: 8 }, { free: true }),
  f('filter-014', 'Deep Mono', 'Black & White', 'Deep contrast monochrome.',
    { monochrome: true, contrast: 34, shadows: -12, clarity: 14, vignette: 16 }, { free: true }),
  f('filter-015', 'Silver Grain', 'Black & White', 'Silver gelatin grain feel.',
    { monochrome: true, contrast: 18, grain: 24, fade: 12, vignette: 14 }, { free: true }),
  f('filter-016', 'Retro Print', 'Retro', 'Retro print warmth and soft focus.',
    { temperature: 22, softBlur: 14, fade: 16, saturation: 12, grain: 12 }, { free: true }),
  f('filter-017', 'Instant Camera', 'Retro', 'Instant-camera soft and warm.',
    { temperature: 18, fade: 20, grain: 16, vignette: 28, saturation: 8, softBlur: 10 }, { free: true }),
  f('filter-018', 'Nostalgic Wash', 'Vintage', 'Nostalgic washed tones.',
    { fade: 24, temperature: 14, saturation: -10, grain: 14, vignette: 16 }, { free: true }),
  f('filter-019', 'Warm Vintage', 'Vintage', 'Warm vintage with soft grain.',
    { temperature: 26, fade: 18, grain: 16, saturation: 10, vignette: 14 }, { free: true }),
  f('filter-020', 'Cool Vintage', 'Vintage', 'Cool vintage fade.',
    { temperature: -8, fade: 22, grain: 14, saturation: -8, vignette: 12 }, { free: true }),
  f('filter-021', 'Pastel Dream', 'Soft', 'Pastel dreamy soft grade.',
    { softBlur: 18, fade: 16, saturation: -8, temperature: 8, bloom: 12 }, { free: true }),
  f('filter-022', 'Rose Glow', 'Portrait', 'Rose-tinted soft glow.',
    { temperature: 12, tint: 10, bloom: 14, softBlur: 12, saturation: 8 }, { free: true }),
  f('filter-023', 'Sunset Kiss', 'Sunset', 'Warm sunset kiss tones.',
    { temperature: 28, tint: 6, saturation: 16, highlights: -10, shadows: 10 }, { free: true }),
  f('filter-024', 'Morning Light', 'Natural', 'Soft morning light lift.',
    { exposure: 6, temperature: 10, shadows: 16, softBlur: 8, contrast: 12 }, { free: true }),
  f('filter-025', 'Cloudy Film', 'Film', 'Cloudy soft film grade.',
    { fade: 18, temperature: -4, grain: 12, contrast: 14, saturation: -6 }, { free: true }),
  f('filter-026', 'Street Fade', 'Street', 'Faded street documentary.',
    { fade: 20, contrast: 16, clarity: 12, saturation: -8, grain: 10 }, { free: true }),
  f('filter-027', 'Night Lift', 'Night', 'Night scene with lifted shadows.',
    { temperature: -12, shadows: 22, contrast: 18, grain: 10, vignette: 20 }, { free: true }),
  f('filter-028', 'Blue Hour', 'Cool', 'Blue hour cool atmosphere.',
    { temperature: -18, tint: -4, shadows: 14, contrast: 16, vignette: 16 }, { free: true }),
  f('filter-029', 'Café Warmth', 'Warm', 'Café interior warmth.',
    { temperature: 24, tint: 6, shadows: 10, saturation: 12, vignette: 12 }, { free: true }),
  f('filter-030', 'Food Rich', 'Food', 'Rich food color and contrast.',
    { saturation: 26, vibrance: 20, contrast: 22, clarity: 14, temperature: 8 }, { free: true }),
  f('filter-031', 'Travel Bright', 'Travel', 'Bright travel-ready grade.',
    { exposure: 8, vibrance: 18, contrast: 16, saturation: 14, clarity: 10 }, { free: true }),
  f('filter-032', 'Skin Balance', 'Portrait', 'Balanced skin-friendly portrait.',
    { temperature: 8, softBlur: 10, shadows: 12, saturation: 6, contrast: 12, clarity: -4 }, { free: true }),
  f('filter-033', 'Soft Beauty', 'Portrait', 'Soft beauty finish.',
    { softBlur: 16, clarity: -12, bloom: 12, temperature: 8, saturation: 6 }, { free: true }),
  f('filter-034', 'Natural Portrait', 'Portrait', 'Natural portrait with gentle lift.',
    { shadows: 14, temperature: 6, contrast: 14, vibrance: 10, softBlur: 6 }, { free: true }),
  f('filter-035', 'Crisp Detail', 'Professional', 'Crisp detail and clarity.',
    { clarity: 24, sharpening: 18, contrast: 20, vibrance: 12, shadows: 6 }, { free: true }),
  f('filter-036', 'Gentle Contrast', 'Natural', 'Gentle contrast without harshness.',
    { contrast: 14, shadows: 10, highlights: -6, vibrance: 10, clarity: 8 }, { free: true }),
  f('filter-037', 'Rich Color', 'Natural', 'Rich saturated color.',
    { saturation: 28, vibrance: 18, contrast: 18, clarity: 10 }, { free: true }),
  f('filter-038', 'Muted Color', 'Soft', 'Muted desaturated color.',
    { saturation: -18, fade: 14, contrast: 12, temperature: 4, vignette: 10 }, { free: true }),
  f('filter-039', 'Classic Fade', 'Film', 'Classic film fade.',
    { fade: 26, grain: 14, contrast: 12, temperature: 8, vignette: 14 }, { free: true }),
  f('filter-040', 'Analog Touch', 'Film', 'Analog film touch with grain.',
    { grain: 22, fade: 14, contrast: 16, temperature: 10, vignette: 12, saturation: -4 }, { free: true }),
  f('filter-041', 'Cinema Ember', 'Cinematic', 'Warm ember cinematic grade.',
    { temperature: 18, contrast: 26, vignette: 24, shadows: 8, grain: 10, saturation: 12 }, { tier: 'ai+', cost: 8 }),
  f('filter-042', 'Cinema Teal', 'Cinematic', 'Teal shadows with warm highlights.',
    { temperature: -10, tint: -6, contrast: 26, vignette: 22, shadows: 10 }, { tier: 'ai+', cost: 8 }),
  f('filter-043', 'Midnight Frame', 'Cinematic', 'Midnight cool cinematic frame.',
    { temperature: -16, contrast: 28, vignette: 30, grain: 12, shadows: 12 }, { tier: 'ai+', cost: 8 }),
  f('filter-044', 'Golden Cinema', 'Cinematic', 'Golden cinematic warmth.',
    { temperature: 22, contrast: 24, vignette: 20, saturation: 14, highlights: -8 }, { tier: 'ai+', cost: 8 }),
  f('filter-045', 'Moody Silver', 'Moody', 'Moody silver desaturated grade.',
    { saturation: -20, contrast: 24, fade: 12, vignette: 22, grain: 10 }, { tier: 'ai+', cost: 8 }),
  f('filter-046', 'Noir Depth', 'Black & White', 'Deep noir with crushed blacks.',
    { monochrome: true, contrast: 42, shadows: -18, vignette: 32, grain: 14, clarity: 12 }, { tier: 'ai+', cost: 8 }),
  f('filter-047', 'Velvet Shadow', 'Moody', 'Velvet soft shadows.',
    { shadows: 18, softBlur: 14, contrast: 16, fade: 10, vignette: 18, temperature: -4 }, { tier: 'ai+', cost: 8 }),
  f('filter-048', 'Editorial Skin', 'Fashion', 'Editorial skin-friendly contrast.',
    { contrast: 22, clarity: 8, temperature: 6, softBlur: 8, saturation: 8, vignette: 12 }, { tier: 'ai+', cost: 8 }),
  f('filter-049', 'Fashion Contrast', 'Fashion', 'High fashion contrast.',
    { contrast: 32, clarity: 16, sharpening: 12, saturation: 10, vignette: 16 }, { tier: 'ai+', cost: 8 }),
  f('filter-050', 'Street Cinema', 'Street', 'Street cinema grit.',
    { contrast: 30, clarity: 20, temperature: -6, grain: 12, vignette: 20, saturation: 8 }, { tier: 'ai+', cost: 8 }),
  f('filter-051', 'Neon District', 'Neon', 'Neon district magenta/cyan push.',
    { style: 'neon', saturation: 28, contrast: 26, bloom: 20, temperature: -8, vignette: 18 }, { tier: 'ai+', cost: 8, animated: true }),
  f('filter-052', 'Electric Night', 'Neon', 'Electric night glow.',
    { style: 'neon', saturation: 32, bloom: 24, contrast: 24, temperature: -12, vignette: 22 }, { tier: 'ai+', cost: 8, animated: true }),
  f('filter-053', 'Dream Film', 'Film', 'Dreamy film with soft halation.',
    { softBlur: 16, bloom: 18, fade: 14, grain: 12, temperature: 10, contrast: 14 }, { tier: 'ai+', cost: 8, animated: true }),
  f('filter-054', 'Retro Neon', 'Neon', 'Retro neon with grain.',
    { style: 'neon', saturation: 26, grain: 18, contrast: 22, temperature: -6, fade: 8 }, { tier: 'ai+', cost: 8 }),
  f('filter-055', 'Analog Heat', 'Warm', 'Analog heat warmth.',
    { temperature: 30, tint: 8, grain: 16, contrast: 18, fade: 10, vignette: 14 }, { tier: 'ai+', cost: 8 }),
  f('filter-056', 'Film Dust', 'Film', 'Dusty film texture.',
    { grain: 28, fade: 18, contrast: 16, temperature: 8, vignette: 16, saturation: -6 }, { tier: 'ai+', cost: 8 }),
  f('filter-057', 'Light Leak', 'Vintage', 'Soft light-leak warmth.',
    { temperature: 24, fade: 20, bloom: 16, saturation: 12, vignette: 24, grain: 10 }, { tier: 'ai+', cost: 8 }),
  f('filter-058', 'Grain Motion', 'Film', 'Strong grain motion feel.',
    { grain: 32, contrast: 18, fade: 12, temperature: 6, vignette: 14 }, { tier: 'ai+', cost: 8 }),
  f('filter-059', 'Soft Halation', 'Soft', 'Soft halation bloom.',
    { bloom: 28, softBlur: 18, clarity: -12, fade: 12, temperature: 8 }, { tier: 'ai+', cost: 8 }),
  f('filter-060', 'Dramatic Portrait', 'Portrait', 'Dramatic portrait contrast.',
    { contrast: 28, shadows: -8, vignette: 24, clarity: 12, temperature: 6, saturation: 8 }, { tier: 'ai+', cost: 8 }),
  f('filter-061', 'Window Cinema', 'Cinematic', 'Window-light cinema feel.',
    { contrast: 22, shadows: 16, temperature: 8, vignette: 18, softBlur: 6, highlights: -10 }, { tier: 'ai+', cost: 8 }),
  f('filter-062', 'Golden Hour Pro', 'Sunset', 'Pro golden hour grade.',
    { temperature: 32, tint: 8, saturation: 18, highlights: -12, shadows: 12, vignette: 14 }, { tier: 'ai+', cost: 8 }),
  f('filter-063', 'Blue Hour Pro', 'Cool', 'Pro blue hour atmosphere.',
    { temperature: -22, tint: -6, shadows: 16, contrast: 20, vignette: 18, grain: 8 }, { tier: 'ai+', cost: 8 }),
  f('filter-064', 'Travel Cinema', 'Travel', 'Travel cinematic grade.',
    { contrast: 24, vibrance: 16, vignette: 16, temperature: 8, clarity: 12, grain: 6 }, { tier: 'ai+', cost: 8 }),
  f('filter-065', 'Urban Drama', 'Dramatic', 'Urban dramatic contrast.',
    { contrast: 36, clarity: 18, vignette: 26, shadows: -10, saturation: 8 }, { tier: 'ai+', cost: 8 }),
  f('filter-066', 'Documentary Tone', 'Street', 'Documentary neutral tone.',
    { contrast: 18, saturation: -8, fade: 8, clarity: 12, grain: 8, temperature: 2 }, { tier: 'ai+', cost: 8 }),
  f('filter-067', 'Music Video', 'Cinematic', 'Music-video punchy grade.',
    { contrast: 30, saturation: 22, vibrance: 18, vignette: 20, clarity: 14 }, { tier: 'ai+', cost: 8 }),
  f('filter-068', 'Night Portrait', 'Portrait', 'Night portrait cool lift.',
    { temperature: -10, shadows: 20, contrast: 18, softBlur: 8, vignette: 22, grain: 8 }, { tier: 'ai+', cost: 8 }),
  f('filter-069', 'Cinema Pastel', 'Cinematic', 'Pastel cinematic softness.',
    { fade: 18, softBlur: 12, saturation: -10, temperature: 8, contrast: 12, vignette: 14 }, { tier: 'ai+', cost: 8 }),
  f('filter-070', 'Desaturated Film', 'Film', 'Desaturated film look.',
    { saturation: -22, fade: 16, grain: 14, contrast: 18, vignette: 16 }, { tier: 'ai+', cost: 8 }),
  f('filter-071', 'Rich Negative', 'Film', 'Rich negative-inspired density.',
    { contrast: 28, saturation: 16, shadows: -6, grain: 12, vignette: 18, temperature: 6 }, { tier: 'ai+', cost: 8 }),
  f('filter-072', 'Matte Cinema', 'Cinematic', 'Matte cinema grade.',
    { fade: 24, contrast: 20, vignette: 20, saturation: -8, grain: 8 }, { tier: 'ai+', cost: 8 }),
  f('filter-073', 'High Contrast Film', 'Film', 'High contrast film punch.',
    { contrast: 38, grain: 16, vignette: 22, shadows: -12, saturation: 10 }, { tier: 'ai+', cost: 8 }),
  f('filter-074', 'Low Contrast Film', 'Film', 'Low contrast soft film.',
    { contrast: 8, fade: 20, grain: 14, softBlur: 8, temperature: 6 }, { tier: 'ai+', cost: 8 }),
  f('filter-075', 'Modern Film Grade', 'Film', 'Modern clean film grade.',
    { contrast: 20, grain: 10, fade: 8, vibrance: 12, clarity: 10, vignette: 12 }, { tier: 'ai+', cost: 8 }),
  f('filter-076', 'Large Format Epic', 'Professional', 'Large-format inspired clarity and depth.',
    { clarity: 28, contrast: 26, sharpening: 16, vignette: 18, shadows: 8, vibrance: 12 }, { tier: 'premium', cost: 12 }),
  f('filter-077', 'Ultra Cinema', 'Cinematic', 'Ultra cinematic contrast and vignette.',
    { contrast: 34, vignette: 34, grain: 12, shadows: -8, temperature: -4, saturation: 10 }, { tier: 'premium', cost: 12 }),
  f('filter-078', 'Hyper Detail', 'Professional', 'Hyper detail clarity boost.',
    { clarity: 36, sharpening: 24, contrast: 22, microcontrast: 18, vibrance: 10 }, { tier: 'premium', cost: 12 }),
  f('filter-079', 'IMAX Inspired', 'Cinematic', 'IMAX-inspired epic contrast frame.',
    { contrast: 32, vignette: 28, clarity: 20, shadows: -6, saturation: 12, grain: 8 }, { tier: 'premium', cost: 12 }),
  f('filter-080', 'Grand Cinema', 'Cinematic', 'Grand cinematic scale grade.',
    { contrast: 30, vignette: 30, temperature: 6, grain: 10, shadows: 8, vibrance: 14 }, { tier: 'premium', cost: 12 }),
  f('filter-081', 'Widescreen Drama', 'Dramatic', 'Widescreen dramatic punch.',
    { contrast: 36, vignette: 32, clarity: 16, shadows: -10, saturation: 10 }, { tier: 'premium', cost: 12 }),
  f('filter-082', 'Deep Dynamic', 'Professional', 'Deep dynamic range inspired tone.',
    { shadows: 20, highlights: -16, contrast: 18, clarity: 14, vibrance: 12 }, { tier: 'premium', cost: 12 }),
  f('filter-083', 'Luxury Portrait', 'Portrait', 'Luxury portrait polish.',
    { softBlur: 12, bloom: 14, temperature: 10, contrast: 18, vignette: 16, saturation: 8, clarity: 6 }, { tier: 'premium', cost: 12 }),
  f('filter-084', 'Studio Master', 'Professional', 'Studio master balanced grade.',
    { contrast: 22, clarity: 16, sharpening: 12, shadows: 10, vibrance: 12, vignette: 10 }, { tier: 'premium', cost: 12 }),
  f('filter-085', 'Editorial Master', 'Fashion', 'Editorial master fashion grade.',
    { contrast: 28, clarity: 14, saturation: 12, vignette: 18, temperature: 4, sharpening: 10 }, { tier: 'premium', cost: 12 }),
  f('filter-086', 'Night Master', 'Night', 'Night master cool depth.',
    { temperature: -18, contrast: 26, vignette: 32, grain: 14, shadows: 16, saturation: -4 }, { tier: 'premium', cost: 12 }),
  f('filter-087', 'Neon Master', 'Neon', 'Neon master intense glow.',
    { style: 'neon', saturation: 36, bloom: 28, contrast: 28, temperature: -10, vignette: 24 }, { tier: 'premium', cost: 12 }),
  f('filter-088', 'Desert Epic', 'Landscape', 'Desert epic warm drama.',
    { temperature: 28, contrast: 28, clarity: 18, vignette: 20, saturation: 14, grain: 8 }, { tier: 'premium', cost: 12 }),
  f('filter-089', 'Oceanic Cinema', 'Landscape', 'Oceanic cool cinema grade.',
    { temperature: -14, tint: -4, contrast: 24, vignette: 18, saturation: 10, clarity: 12 }, { tier: 'premium', cost: 12 }),
  f('filter-090', 'Mountain Grandeur', 'Landscape', 'Mountain grandeur clarity.',
    { clarity: 26, contrast: 26, temperature: -6, vignette: 16, shadows: 10, vibrance: 12 }, { tier: 'premium', cost: 12 }),
  f('filter-091', 'Black Glass', 'Black & White', 'Black glass deep mono.',
    { monochrome: true, contrast: 44, shadows: -20, vignette: 36, clarity: 18, grain: 10 }, { tier: 'premium', cost: 12 }),
  f('filter-092', 'Platinum Mono', 'Black & White', 'Platinum mono soft highlight.',
    { monochrome: true, contrast: 20, fade: 14, grain: 12, vignette: 14, softBlur: 6 }, { tier: 'premium', cost: 12 }),
  f('filter-093', 'Velvet Cinema', 'Cinematic', 'Velvet cinema soft drama.',
    { softBlur: 14, contrast: 24, vignette: 26, fade: 10, temperature: 6, saturation: 8 }, { tier: 'premium', cost: 12 }),
  f('filter-094', 'Director Grade', 'Cinematic', 'Director-style cinematic grade.',
    { contrast: 28, vignette: 28, temperature: -6, tint: -4, grain: 10, saturation: 6, shadows: 8 }, { tier: 'premium', cost: 12 }),
  f('filter-095', 'Festival Frame', 'Cinematic', 'Festival film frame look.',
    { contrast: 26, grain: 16, fade: 12, vignette: 22, temperature: 8, saturation: 12 }, { tier: 'premium', cost: 12 }),
  f('filter-096', 'Master Contrast', 'Dramatic', 'Master contrast drama.',
    { contrast: 42, shadows: -16, vignette: 30, clarity: 16, saturation: 8 }, { tier: 'premium', cost: 12 }),
  f('filter-097', 'Ultra Natural', 'Natural', 'Ultra natural clean polish.',
    { contrast: 18, clarity: 16, vibrance: 14, sharpening: 12, shadows: 8, temperature: 4 }, { tier: 'premium', cost: 12 }),
  f('filter-098', 'Hyper Real Portrait', 'Portrait', 'Hyper-real portrait detail.',
    { clarity: 22, sharpening: 16, contrast: 20, softBlur: 4, temperature: 6, saturation: 8, vignette: 12 }, { tier: 'premium', cost: 12 }),
  f('filter-099', 'Detail 16K', 'Professional', '16K-detail inspired microclarity aesthetic.',
    { clarity: 32, sharpening: 22, microcontrast: 20, contrast: 20, vibrance: 10, shadows: 6 }, { tier: 'premium', cost: 12 }),
  f('filter-100', 'Motio Master Grade', 'Cinematic', 'Signature Motio2edit master grade.',
    { contrast: 28, vignette: 24, temperature: 8, vibrance: 16, clarity: 14, grain: 8, shadows: 10 }, { tier: 'premium', cost: 12 }),
];
