import { FilterDefinition } from './filter-types';
import { createAttribution, createUnlockMetadata } from '../shared/metadata';

/** Categories: Cool, Street, Travel, Landscape, Food (5 each) */
export const FILTERS_051_075: FilterDefinition[] = [
  // Cool (5)
  {id:'filter-051',name:'Arctic Blue',category:'Cool',description:'Arctic Blue — deep cool blue with crisp contrast.',visualDescription:'Deep arctic blue, crisp edges.',icon:'icon-filter-051',previewKey:'preview-filter-051',processingProfile:{temperature:-34,tint:-6,contrast:28,clarity:18,saturation:8},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-052',name:'Ice Glass',category:'Cool',description:'Ice Glass — crystalline cool with high clarity.',visualDescription:'Ice glass, high clarity, cool sparkle.',icon:'icon-filter-052',previewKey:'preview-filter-052',processingProfile:{temperature:-26,clarity:28,sharpening:22,contrast:20,highlights:10},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-053',name:'Cyan Drift',category:'Cool',description:'Cyan Drift — cyan-leaning cool grade with soft shadows.',visualDescription:'Cyan drift, soft cool shadows.',icon:'icon-filter-053',previewKey:'preview-filter-053',processingProfile:{temperature:-20,tint:-12,shadows:18,saturation:12,vibrance:14},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-054',name:'Steel Cool',category:'Cool',description:'Steel Cool — industrial steel cool with hard microcontrast.',visualDescription:'Steel cool, hard microcontrast.',icon:'icon-filter-054',previewKey:'preview-filter-054',processingProfile:{temperature:-18,contrast:30,microcontrast:24,clarity:20,saturation:-8},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-055',name:'Twilight Cool',category:'Cool',description:'Twilight Cool — blue-hour cool with gentle atmosphere.',visualDescription:'Twilight cool, gentle blue hour.',icon:'icon-filter-055',previewKey:'preview-filter-055',processingProfile:{temperature:-28,atmosphere:20,shadows:22,vignette:20,saturation:6},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},

  // Street (5)
  {id:'filter-056',name:'Street Punch',category:'Street',description:'Street Punch — high contrast urban street grit.',visualDescription:'Street grit, high contrast, hard edges.',icon:'icon-filter-056',previewKey:'preview-filter-056',processingProfile:{contrast:36,clarity:24,sharpening:18,saturation:12,vignette:22},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-057',name:'Neon Alley',category:'Street',description:'Neon Alley — neon street glow with magenta/cyan push.',visualDescription:'Neon alley, magenta cyan glow.',icon:'icon-filter-057',previewKey:'preview-filter-057',processingProfile:{style:'neon',saturation:30,contrast:28,bloom:24,temperature:-8,vignette:20},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-058',name:'Grit Film',category:'Street',description:'Grit Film — heavy grain street film look.',visualDescription:'Heavy grain, street film grit.',icon:'icon-filter-058',previewKey:'preview-filter-058',processingProfile:{grain:38,contrast:26,saturation:-10,fade:12,vignette:28},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-059',name:'Concrete Grey',category:'Street',description:'Concrete Grey — desaturated concrete urban tone.',visualDescription:'Concrete grey, urban desat.',icon:'icon-filter-059',previewKey:'preview-filter-059',processingProfile:{saturation:-32,contrast:24,clarity:16,temperature:-6,vignette:18},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-060',name:'Rush Hour',category:'Street',description:'Rush Hour — motion-friendly punchy street grade.',visualDescription:'Rush hour punch, motion-ready.',icon:'icon-filter-060',previewKey:'preview-filter-060',processingProfile:{contrast:30,vibrance:22,clarity:18,temperature:6,sharpening:14},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},

  // Travel (5)
  {id:'filter-061',name:'Wanderlust',category:'Travel',description:'Wanderlust — vivid travel color with open shadows.',visualDescription:'Vivid travel, open shadows.',icon:'icon-filter-061',previewKey:'preview-filter-061',processingProfile:{saturation:26,vibrance:24,shadows:20,contrast:18,clarity:12},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-062',name:'Passport Tone',category:'Travel',description:'Passport Tone — warm documentary travel grade.',visualDescription:'Warm documentary travel.',icon:'icon-filter-062',previewKey:'preview-filter-062',processingProfile:{temperature:18,saturation:14,contrast:20,fade:10,grain:12},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-063',name:'Island Light',category:'Travel',description:'Island Light — bright tropical island clarity.',visualDescription:'Tropical clarity, bright island light.',icon:'icon-filter-063',previewKey:'preview-filter-063',processingProfile:{temperature:12,exposure:8,clarity:20,saturation:20,highlights:-10},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-064',name:'Mountain Air',category:'Travel',description:'Mountain Air — cool mountain atmosphere with depth.',visualDescription:'Mountain air, cool depth.',icon:'icon-filter-064',previewKey:'preview-filter-064',processingProfile:{temperature:-14,atmosphere:18,clarity:22,contrast:22,vignette:16},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-065',name:'City Guide',category:'Travel',description:'City Guide — balanced travel city grade with local color.',visualDescription:'Balanced city travel, local color.',icon:'icon-filter-065',previewKey:'preview-filter-065',processingProfile:{vibrance:20,contrast:22,clarity:14,temperature:4,sharpening:12},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},

  // Landscape (5)
  {id:'filter-066',name:'Peak Clarity',category:'Landscape',description:'Peak Clarity — mountain peak clarity and deep sky contrast.',visualDescription:'Peak clarity, deep sky.',icon:'icon-filter-066',previewKey:'preview-filter-066',processingProfile:{clarity:28,contrast:26,sharpening:20,temperature:-8,vibrance:12,vignette:14},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-067',name:'Valley Soft',category:'Landscape',description:'Valley Soft — soft valley atmosphere with lifted haze.',visualDescription:'Soft valley, lifted haze.',icon:'icon-filter-067',previewKey:'preview-filter-067',processingProfile:{atmosphere:24,softBlur:14,fade:16,contrast:12,shadows:18,temperature:4},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-068',name:'Coastal Breeze',category:'Landscape',description:'Coastal Breeze — cool coastal clarity and open highlights.',visualDescription:'Coastal cool, open highlights.',icon:'icon-filter-068',previewKey:'preview-filter-068',processingProfile:{temperature:-16,clarity:22,highlights:-14,dynamicRange:28,saturation:10},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-069',name:'Forest Deep',category:'Landscape',description:'Forest Deep — deep green forest with rich shadows.',visualDescription:'Deep forest greens, rich shadows.',icon:'icon-filter-069',previewKey:'preview-filter-069',processingProfile:{saturation:18,shadows:-16,contrast:22,temperature:6,vignette:20,clarity:14},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-070',name:'Desert Heat',category:'Landscape',description:'Desert Heat — hot desert warmth and hard light.',visualDescription:'Desert heat, hard light.',icon:'icon-filter-070',previewKey:'preview-filter-070',processingProfile:{temperature:30,contrast:28,clarity:18,highlights:8,saturation:14,vignette:16},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},

  // Food (5)
  {id:'filter-071',name:'Fresh Plate',category:'Food',description:'Fresh Plate — appetizing saturation and clean food light.',visualDescription:'Fresh plate, appetizing color.',icon:'icon-filter-071',previewKey:'preview-filter-071',processingProfile:{saturation:28,vibrance:24,clarity:20,contrast:18,sharpening:14,highlights:-10},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-072',name:'Rustic Table',category:'Food',description:'Rustic Table — warm rustic food grade with soft grain.',visualDescription:'Rustic warm food, soft grain.',icon:'icon-filter-072',previewKey:'preview-filter-072',processingProfile:{temperature:22,saturation:16,grain:16,contrast:16,vignette:18,fade:8},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-073',name:'Chef Pop',category:'Food',description:'Chef Pop — high-pop food color and microcontrast.',visualDescription:'Chef pop, high color snap.',icon:'icon-filter-073',previewKey:'preview-filter-073',processingProfile:{vibrance:30,clarity:24,contrast:22,sharpening:16,saturation:18},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-074',name:'Bakery Warm',category:'Food',description:'Bakery Warm — bakery warmth and soft glow.',visualDescription:'Bakery warm glow.',icon:'icon-filter-074',previewKey:'preview-filter-074',processingProfile:{temperature:26,bloom:20,softBlur:10,saturation:14,contrast:12},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-075',name:'Market Fresh',category:'Food',description:'Market Fresh — bright market produce clarity.',visualDescription:'Market fresh, bright produce.',icon:'icon-filter-075',previewKey:'preview-filter-075',processingProfile:{exposure:6,saturation:22,clarity:18,contrast:16,temperature:8},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
];
