import { FilterDefinition } from './filter-types';
import { createAttribution, createUnlockMetadata } from '../shared/metadata';

/** Categories: Fashion, Dramatic, Soft, Professional, Warm (5 each) */
export const FILTERS_076_100: FilterDefinition[] = [
  // Fashion (5)
  {id:'filter-076',name:'Runway Clean',category:'Fashion',description:'Runway Clean — clean fashion with accurate skin and fabric detail.',visualDescription:'Runway clean, fabric detail.',icon:'icon-filter-076',previewKey:'preview-filter-076',processingProfile:{clarity:20,sharpening:18,contrast:16,vibrance:10,highlights:-8},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-077',name:'Editorial Fade',category:'Fashion',description:'Editorial Fade — soft editorial fade with muted contrast.',visualDescription:'Editorial fade, soft contrast.',icon:'icon-filter-077',previewKey:'preview-filter-077',processingProfile:{fade:22,contrast:10,clarity:-6,saturation:-8,vignette:16},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-078',name:'Glamour Glow',category:'Fashion',description:'Glamour Glow — beauty glow with soft bloom.',visualDescription:'Glamour bloom, soft beauty.',icon:'icon-filter-078',previewKey:'preview-filter-078',processingProfile:{bloom:26,softBlur:14,clarity:-12,temperature:8,saturation:10,fade:8},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-079',name:'Street Style',category:'Fashion',description:'Street Style — punchy street fashion contrast.',visualDescription:'Street style punch.',icon:'icon-filter-079',previewKey:'preview-filter-079',processingProfile:{contrast:28,clarity:18,saturation:16,sharpening:14,vignette:14},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-080',name:'Lookbook Soft',category:'Fashion',description:'Lookbook Soft — soft lookbook grade with accurate color.',visualDescription:'Lookbook soft, accurate color.',icon:'icon-filter-080',previewKey:'preview-filter-080',processingProfile:{contrast:12,clarity:-4,vibrance:14,softBlur:8,temperature:4},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},

  // Dramatic (5)
  {id:'filter-081',name:'Drama High',category:'Dramatic',description:'Drama High — high-drama contrast and deep vignette.',visualDescription:'High drama, deep vignette.',icon:'icon-filter-081',previewKey:'preview-filter-081',processingProfile:{contrast:40,shadows:-22,vignette:36,clarity:16,saturation:8},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-082',name:'Epic Wide',category:'Dramatic',description:'Epic Wide — epic wide-scene contrast and atmosphere.',visualDescription:'Epic wide, atmospheric drama.',icon:'icon-filter-082',previewKey:'preview-filter-082',processingProfile:{contrast:32,atmosphere:16,clarity:20,vignette:24,temperature:-4},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-083',name:'Spotlight',category:'Dramatic',description:'Spotlight — spotlight subject with crushed periphery.',visualDescription:'Spotlight subject, crushed edges.',icon:'icon-filter-083',previewKey:'preview-filter-083',processingProfile:{vignette:48,contrast:34,shadows:-18,clarity:14,bloom:12},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-084',name:'Thunder Mood',category:'Dramatic',description:'Thunder Mood — storm drama with cool desat and hard light.',visualDescription:'Thunder mood, hard storm light.',icon:'icon-filter-084',previewKey:'preview-filter-084',processingProfile:{temperature:-18,saturation:-20,contrast:36,clarity:18,vignette:28},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-085',name:'Stage Light',category:'Dramatic',description:'Stage Light — theatrical stage contrast and warm key.',visualDescription:'Stage light, theatrical contrast.',icon:'icon-filter-085',previewKey:'preview-filter-085',processingProfile:{contrast:34,temperature:14,vignette:30,bloom:16,shadows:-14},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},

  // Soft (5)
  {id:'filter-086',name:'Dream Soft',category:'Soft',description:'Dream Soft — dreamy soft focus with gentle bloom.',visualDescription:'Dream soft, gentle bloom.',icon:'icon-filter-086',previewKey:'preview-filter-086',processingProfile:{softBlur:28,bloom:22,clarity:-16,fade:14,contrast:-6},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-087',name:'Silk Glow',category:'Soft',description:'Silk Glow — silk-smooth soft grade with warm lift.',visualDescription:'Silk smooth, warm soft lift.',icon:'icon-filter-087',previewKey:'preview-filter-087',processingProfile:{softBlur:18,bloom:18,temperature:10,clarity:-10,saturation:8},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-088',name:'Pastel Mist',category:'Soft',description:'Pastel Mist — pastel soft mist with lifted blacks.',visualDescription:'Pastel mist, lifted blacks.',icon:'icon-filter-088',previewKey:'preview-filter-088',processingProfile:{fade:24,softBlur:16,saturation:-12,shadows:20,vignette:12},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-089',name:'Cloud Soft',category:'Soft',description:'Cloud Soft — soft cloud-like diffusion.',visualDescription:'Cloud diffusion, soft edges.',icon:'icon-filter-089',previewKey:'preview-filter-089',processingProfile:{softBlur:24,atmosphere:16,contrast:-8,clarity:-12,fade:10},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-090',name:'Whisper Tone',category:'Soft',description:'Whisper Tone — very gentle soft tonal wash.',visualDescription:'Whisper soft tonal wash.',icon:'icon-filter-090',previewKey:'preview-filter-090',processingProfile:{softBlur:12,fade:12,contrast:6,brightness:6,temperature:4},intensityRange:{min:0,max:100,default:80},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},

  // Professional (5)
  {id:'filter-091',name:'Pro Neutral',category:'Professional',description:'Pro Neutral — balanced professional neutral finishing grade.',visualDescription:'Pro neutral finish.',icon:'icon-filter-091',previewKey:'preview-filter-091',processingProfile:{contrast:14,clarity:14,sharpening:14,vibrance:8},intensityRange:{min:0,max:100,default:80},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-092',name:'Product Crisp',category:'Professional',description:'Product Crisp — crisp product presentation with controlled reflections.',visualDescription:'Crisp product, controlled reflections.',icon:'icon-filter-092',previewKey:'preview-filter-092',processingProfile:{sharpening:24,clarity:22,contrast:18,highlights:-12},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(20,false)},
  {id:'filter-093',name:'Editorial Sharp',category:'Professional',description:'Editorial Sharp — editorial sharpness for magazine-style clarity.',visualDescription:'Editorial sharp clarity.',icon:'icon-filter-093',previewKey:'preview-filter-093',processingProfile:{sharpening:26,clarity:24,contrast:18,saturation:6},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(22,false)},
  {id:'filter-094',name:'Studio Clean',category:'Professional',description:'Studio Clean — clean studio light with accurate color.',visualDescription:'Studio clean, accurate color.',icon:'icon-filter-094',previewKey:'preview-filter-094',processingProfile:{contrast:16,clarity:12,vibrance:10,sharpening:12,highlights:-8},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-095',name:'Catalog True',category:'Professional',description:'Catalog True — true-color catalog grade for ecommerce.',visualDescription:'Catalog true color.',icon:'icon-filter-095',previewKey:'preview-filter-095',processingProfile:{saturation:8,vibrance:10,contrast:12,clarity:10,sharpening:10},intensityRange:{min:0,max:100,default:80},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},

  // Warm (5)
  {id:'filter-096',name:'Amber Dust',category:'Warm',description:'Warm amber midtones with soft grain for golden nostalgic warmth.',visualDescription:'Amber warmth, soft grain, golden midtones.',icon:'icon-filter-096',previewKey:'preview-filter-096',processingProfile:{temperature:32,tint:8,grain:22,vibrance:18,contrast:18,vignette:16},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-097',name:'Copper Glow',category:'Warm',description:'Copper-toned highlights with gentle contrast for evening warmth.',visualDescription:'Copper highlights, evening warmth.',icon:'icon-filter-097',previewKey:'preview-filter-097',processingProfile:{temperature:28,contrast:22,highlights:-12,grain:14,saturation:14,vignette:18},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-098',name:'Honey Light',category:'Warm',description:'Honey-colored light wash for soft portrait warmth.',visualDescription:'Honey wash, soft skin tones.',icon:'icon-filter-098',previewKey:'preview-filter-098',processingProfile:{temperature:26,brightness:10,clarity:-8,bloom:18,softBlur:12,saturation:12},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-099',name:'Rust Evening',category:'Warm',description:'Rust-tinted evening look with deeper shadows.',visualDescription:'Rust tones, deeper shadows.',icon:'icon-filter-099',previewKey:'preview-filter-099',processingProfile:{temperature:22,tint:12,shadows:-18,contrast:24,vignette:28,saturation:10},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-100',name:'Saffron Dusk',category:'Warm',description:'Saffron-tinted dusk atmosphere with mild vignette.',visualDescription:'Saffron dusk, warm atmosphere.',icon:'icon-filter-100',previewKey:'preview-filter-100',processingProfile:{temperature:34,saturation:16,vignette:22,fade:12,contrast:16,atmosphere:10},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
];
