import { FilterDefinition } from './filter-types';
import { createAttribution, createUnlockMetadata } from '../shared/metadata';

export const FILTERS_076_100: FilterDefinition[] = [
  // Warm (5)
  {id:'filter-076',name:'Amber Dust',category:'Warm',description:'Warm amber midtones with soft grain for golden nostalgic warmth.',visualDescription:'Amber warmth, soft grain, golden midtones.',icon:'icon-filter-076',previewKey:'preview-filter-076',processingProfile:{temperature:32,tint:8,grain:22,vibrance:18,contrast:18,vignette:16},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-077',name:'Copper Glow',category:'Warm',description:'Copper-toned highlights with gentle contrast for evening warmth.',visualDescription:'Copper highlights, evening warmth.',icon:'icon-filter-077',previewKey:'preview-filter-077',processingProfile:{temperature:28,contrast:22,highlights:-12,grain:14,saturation:14,vignette:18},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-078',name:'Honey Light',category:'Warm',description:'Honey-colored light wash for soft portrait warmth.',visualDescription:'Honey wash, soft skin tones.',icon:'icon-filter-078',previewKey:'preview-filter-078',processingProfile:{temperature:26,brightness:10,clarity:-8,bloom:18,softBlur:12,saturation:12},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-079',name:'Rust Evening',category:'Warm',description:'Rust-tinted evening look with deeper shadows.',visualDescription:'Rust tones, deeper shadows.',icon:'icon-filter-079',previewKey:'preview-filter-079',processingProfile:{temperature:22,tint:12,shadows:-18,contrast:24,vignette:28,saturation:10},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-080',name:'Saffron Dusk',category:'Warm',description:'Saffron-tinted dusk atmosphere with mild vignette.',visualDescription:'Saffron dusk, warm atmosphere.',icon:'icon-filter-080',previewKey:'preview-filter-080',processingProfile:{temperature:34,saturation:16,vignette:22,fade:12,contrast:16,atmosphere:10},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},

  // Cool already covered in 061-065; remaining categories from types: Landscape, Food, Fashion, Dramatic, Soft, Professional
  // Landscape (5)
  {id:'filter-081',name:'Peak Clarity',category:'Landscape',description:'Peak Clarity — mountain peak clarity and deep sky contrast.',visualDescription:'Peak clarity, deep sky.',icon:'icon-filter-081',previewKey:'preview-filter-081',processingProfile:{clarity:28,contrast:26,sharpening:20,temperature:-8,vibrance:12,vignette:14},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-082',name:'Valley Soft',category:'Landscape',description:'Valley Soft — soft valley atmosphere with lifted haze.',visualDescription:'Soft valley, lifted haze.',icon:'icon-filter-082',previewKey:'preview-filter-082',processingProfile:{atmosphere:24,softBlur:14,fade:16,contrast:12,shadows:18,temperature:4},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-083',name:'Coastal Breeze',category:'Landscape',description:'Coastal Breeze — cool coastal clarity and open highlights.',visualDescription:'Coastal cool, open highlights.',icon:'icon-filter-083',previewKey:'preview-filter-083',processingProfile:{temperature:-16,clarity:22,highlights:-14,dynamicRange:28,saturation:10},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-084',name:'Forest Deep',category:'Landscape',description:'Forest Deep — deep green forest with rich shadows.',visualDescription:'Deep forest greens, rich shadows.',icon:'icon-filter-084',previewKey:'preview-filter-084',processingProfile:{saturation:18,shadows:-16,contrast:22,temperature:6,vignette:20,clarity:14},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-085',name:'Desert Heat',category:'Landscape',description:'Desert Heat — hot desert warmth and hard light.',visualDescription:'Desert heat, hard light.',icon:'icon-filter-085',previewKey:'preview-filter-085',processingProfile:{temperature:30,contrast:28,clarity:18,highlights:8,saturation:14,vignette:16},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},

  // Food (5)
  {id:'filter-086',name:'Fresh Plate',category:'Food',description:'Fresh Plate — appetizing saturation and clean food light.',visualDescription:'Fresh plate, appetizing color.',icon:'icon-filter-086',previewKey:'preview-filter-086',processingProfile:{saturation:28,vibrance:24,clarity:20,contrast:18,sharpening:14,highlights:-10},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-087',name:'Rustic Table',category:'Food',description:'Rustic Table — warm rustic food grade with soft grain.',visualDescription:'Rustic warm food, soft grain.',icon:'icon-filter-087',previewKey:'preview-filter-087',processingProfile:{temperature:22,saturation:16,grain:16,contrast:16,vignette:18,fade:8},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-088',name:'Chef Pop',category:'Food',description:'Chef Pop — high-pop food color and microcontrast.',visualDescription:'Chef pop, high color snap.',icon:'icon-filter-088',previewKey:'preview-filter-088',processingProfile:{vibrance:30,clarity:24,contrast:22,sharpening:16,saturation:18},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-089',name:'Bakery Warm',category:'Food',description:'Bakery Warm — bakery warmth and soft glow.',visualDescription:'Bakery warm glow.',icon:'icon-filter-089',previewKey:'preview-filter-089',processingProfile:{temperature:26,bloom:20,softBlur:10,saturation:14,contrast:12},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-090',name:'Market Fresh',category:'Food',description:'Market Fresh — bright market produce clarity.',visualDescription:'Market fresh, bright produce.',icon:'icon-filter-090',previewKey:'preview-filter-090',processingProfile:{exposure:6,saturation:22,clarity:18,contrast:16,temperature:8},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},

  // Fashion (5)
  {id:'filter-091',name:'Runway Clean',category:'Fashion',description:'Runway Clean — clean fashion with accurate skin and fabric detail.',visualDescription:'Runway clean, fabric detail.',icon:'icon-filter-091',previewKey:'preview-filter-091',processingProfile:{clarity:20,sharpening:18,contrast:16,vibrance:10,highlights:-8},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-092',name:'Editorial Fade',category:'Fashion',description:'Editorial Fade — soft editorial fade with muted contrast.',visualDescription:'Editorial fade, soft contrast.',icon:'icon-filter-092',previewKey:'preview-filter-092',processingProfile:{fade:22,contrast:10,clarity:-6,saturation:-8,vignette:16},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-093',name:'Glamour Glow',category:'Fashion',description:'Glamour Glow — beauty glow with soft bloom.',visualDescription:'Glamour bloom, soft beauty.',icon:'icon-filter-093',previewKey:'preview-filter-093',processingProfile:{bloom:26,softBlur:14,clarity:-12,temperature:8,saturation:10,fade:8},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-094',name:'Street Style',category:'Fashion',description:'Street Style — punchy street fashion contrast.',visualDescription:'Street style punch.',icon:'icon-filter-094',previewKey:'preview-filter-094',processingProfile:{contrast:28,clarity:18,saturation:16,sharpening:14,vignette:14},intensityRange:{min:0,max:100,default:88},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},
  {id:'filter-095',name:'Lookbook Soft',category:'Fashion',description:'Lookbook Soft — soft lookbook grade with accurate color.',visualDescription:'Lookbook soft, accurate color.',icon:'icon-filter-095',previewKey:'preview-filter-095',processingProfile:{contrast:12,clarity:-4,vibrance:14,softBlur:8,temperature:4},intensityRange:{min:0,max:100,default:85},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(12,false)},

  // Dramatic (5) — use remaining slots; types has Dramatic, Soft, Professional
  {id:'filter-096',name:'Drama High',category:'Dramatic',description:'Drama High — high-drama contrast and deep vignette.',visualDescription:'High drama, deep vignette.',icon:'icon-filter-096',previewKey:'preview-filter-096',processingProfile:{contrast:40,shadows:-22,vignette:36,clarity:16,saturation:8},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-097',name:'Epic Wide',category:'Dramatic',description:'Epic Wide — epic wide-scene contrast and atmosphere.',visualDescription:'Epic wide, atmospheric drama.',icon:'icon-filter-097',previewKey:'preview-filter-097',processingProfile:{contrast:32,atmosphere:16,clarity:20,vignette:24,temperature:-4},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-098',name:'Spotlight',category:'Dramatic',description:'Spotlight — spotlight subject with crushed periphery.',visualDescription:'Spotlight subject, crushed edges.',icon:'icon-filter-098',previewKey:'preview-filter-098',processingProfile:{vignette:48,contrast:34,shadows:-18,clarity:14,bloom:12},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-099',name:'Thunder Mood',category:'Dramatic',description:'Thunder Mood — storm drama with cool desat and hard light.',visualDescription:'Thunder mood, hard storm light.',icon:'icon-filter-099',previewKey:'preview-filter-099',processingProfile:{temperature:-18,saturation:-20,contrast:36,clarity:18,vignette:28},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
  {id:'filter-100',name:'Stage Light',category:'Dramatic',description:'Stage Light — theatrical stage contrast and warm key.',visualDescription:'Stage light, theatrical contrast.',icon:'icon-filter-100',previewKey:'preview-filter-100',processingProfile:{contrast:34,temperature:14,vignette:30,bloom:16,shadows:-14},intensityRange:{min:0,max:100,default:90},supportsPreview:true as const,supportsFullResolution:true as const,supportsCamera:false as const,developerNotes:'',attribution:createAttribution(),unlock:createUnlockMetadata(15,false)},
];
