/**
 * Motio2edit 100-filter catalog — original short-name recipes.
 * Common 40 (free) · AI+ 35 · Premium 25
 * Distinct looks only. No proprietary preset clones.
 */
import { FilterDefinition } from './filter-types';
import { createAttribution, createUnlockMetadata } from '../shared/metadata';

const IR = { min: 0, max: 100, default: 85 } as const;

function f(
  id: string,
  name: string,
  category: FilterDefinition['category'],
  desc: string,
  profile: FilterDefinition['processingProfile'],
  opts: { free?: boolean; tier?: 'ai+' | 'pro' | 'premium'; animated?: boolean; cost?: number } = {},
): FilterDefinition {
  const isFree = !!opts.free;
  return {
    id,
    name,
    category,
    description: desc,
    visualDescription: desc,
    icon: `icon-${id}`,
    previewKey: `preview-${id}`,
    processingProfile: profile,
    intensityRange: IR,
    supportsPreview: true as const,
    supportsFullResolution: true as const,
    supportsCamera: false as const,
    developerNotes: '',
    attribution: createAttribution(),
    unlock: createUnlockMetadata(isFree ? 0 : opts.cost ?? 12, isFree),
    ...(isFree ? {} : { tier: opts.tier ?? 'premium' }),
    ...(opts.animated ? { animatedThumb: true } : {}),
  };
}

export const FILTERS_CURATED: FilterDefinition[] = [
  f('filter-001', 'Vivid Pop', 'Natural',
    'Everyday punchy color with clean midtones for social and lifestyle shots.',
    { contrast: 22, saturation: 24, vibrance: 20, clarity: 12, shadows: 10 }, { free: true }),
  f('filter-002', 'Warm Skin', 'Portrait',
    'Gentle warm portrait grade that keeps natural skin texture.',
    { temperature: 14, softBlur: 10, shadows: 12, saturation: 6, contrast: 12, clarity: -4 }, { free: true }),
  f('filter-003', 'Soft Glow', 'Soft',
    'Soft luminous highlights with airy contrast for dreamy portraits.',
    { softBlur: 18, bloom: 16, clarity: -10, fade: 8, contrast: 10, temperature: 6 }, { free: true }),
  f('filter-004', 'Clean Day', 'Natural',
    'Balanced daylight grade with clear midtones and mild clarity.',
    { contrast: 16, vibrance: 14, clarity: 10, temperature: 4, sharpening: 8 }, { free: true }),
  f('filter-005', 'Fresh Air', 'Natural',
    'Open outdoor lift with slightly cooler sky-friendly tones.',
    { exposure: 6, shadows: 18, contrast: 14, vibrance: 14, temperature: -2 }, { free: true }),
  f('filter-006', 'Golden Skin', 'Portrait',
    'Warm golden skin midtones without heavy smoothing.',
    { temperature: 18, tint: 4, softBlur: 8, shadows: 10, saturation: 8, contrast: 12 }, { free: true }),
  f('filter-007', 'Urban Clean', 'Street',
    'Crisp street grade with urban contrast and mild vignette.',
    { contrast: 24, clarity: 16, sharpening: 12, saturation: 8, vignette: 12 }, { free: true }),
  f('filter-008', 'Cool Street', 'Street',
    'Cooler street grit with stronger midtone contrast.',
    { temperature: -10, contrast: 26, clarity: 14, saturation: 6, vignette: 14 }, { free: true }),
  f('filter-009', 'Soft Matte', 'Soft',
    'Lifted blacks and matte soft finish for modern lifestyle looks.',
    { fade: 20, contrast: 10, saturation: -6, softBlur: 6, vignette: 8 }, { free: true }),
  f('filter-010', 'B/W', 'Black & White',
    'Clean balanced monochrome with natural tonal range.',
    { monochrome: true, contrast: 20, clarity: 8, grain: 4, vignette: 6 }, { free: true }),
  f('filter-011', 'Deep B/W', 'Black & White',
    'Stronger blacks and dramatic separation while keeping detail.',
    { monochrome: true, contrast: 36, shadows: -14, clarity: 12, vignette: 14, grain: 6 }, { free: true }),
  f('filter-012', 'Silver Grain', 'Black & White',
    'Soft silver gelatin feel with visible grain.',
    { monochrome: true, contrast: 16, grain: 22, fade: 10, vignette: 12 }, { free: true }),
  f('filter-013', 'Vintage 70', 'Vintage',
    'Warm analog 70s fade with muted color and soft grain.',
    { temperature: 24, fade: 22, grain: 16, saturation: -8, contrast: 12, vignette: 14 }, { free: true }),
  f('filter-014', 'Vintage 90', 'Vintage',
    'Cooler 90s nostalgic cast with firmer contrast and grain.',
    { temperature: -4, fade: 16, grain: 18, contrast: 18, saturation: -6, vignette: 12 }, { free: true }),
  f('filter-015', 'Retro Fade', 'Retro',
    'Soft retro wash with warm midtones and gentle blur.',
    { temperature: 16, fade: 18, softBlur: 10, grain: 12, saturation: 8 }, { free: true }),
  f('filter-016', 'Instant Cam', 'Retro',
    'Instant-camera warmth, soft edges, and vignette.',
    { temperature: 16, fade: 18, grain: 14, vignette: 26, softBlur: 8, saturation: 6 }, { free: true }),
  f('filter-017', 'Pastel Soft', 'Soft',
    'Muted pastel colors with soft bloom for gentle moods.',
    { softBlur: 14, fade: 14, saturation: -10, temperature: 6, bloom: 10 }, { free: true }),
  f('filter-018', 'Rose Glow', 'Portrait',
    'Subtle rose-tinted glow for flattering portrait light.',
    { temperature: 10, tint: 8, bloom: 12, softBlur: 10, saturation: 6 }, { free: true }),
  f('filter-019', 'Sunset Soft', 'Sunset',
    'Soft sunset warmth with restrained highlights.',
    { temperature: 24, tint: 4, saturation: 12, highlights: -10, shadows: 8 }, { free: true }),
  f('filter-020', 'Morning', 'Natural',
    'Soft morning lift with gentle warmth.',
    { exposure: 6, temperature: 8, shadows: 14, softBlur: 6, contrast: 12 }, { free: true }),
  f('filter-021', 'Cloudy Film', 'Film',
    'Soft cloudy film grade with mild desaturation.',
    { fade: 16, temperature: -4, grain: 10, contrast: 12, saturation: -8 }, { free: true }),
  f('filter-022', 'Street Fade', 'Street',
    'Documentary street fade with restrained color.',
    { fade: 16, contrast: 14, clarity: 10, saturation: -10, grain: 8 }, { free: true }),
  f('filter-023', 'Night Lift', 'Night',
    'Night scene with lifted shadows and cool cast.',
    { temperature: -12, shadows: 20, contrast: 16, grain: 8, vignette: 16 }, { free: true }),
  f('filter-024', 'Blue Hour', 'Cool',
    'Cool blue-hour atmosphere for dusk and city lights.',
    { temperature: -18, tint: -4, shadows: 12, contrast: 14, vignette: 14 }, { free: true }),
  f('filter-025', 'Café Warm', 'Warm',
    'Interior café warmth with soft shadows.',
    { temperature: 20, tint: 4, shadows: 8, saturation: 10, vignette: 10 }, { free: true }),
  f('filter-026', 'Food Rich', 'Food',
    'Rich food color and contrast for plates and product shots.',
    { saturation: 24, vibrance: 18, contrast: 20, clarity: 12, temperature: 6 }, { free: true }),
  f('filter-027', 'Travel Bright', 'Travel',
    'Bright travel-ready grade for outdoor and landmarks.',
    { exposure: 6, vibrance: 16, contrast: 14, saturation: 12, clarity: 8 }, { free: true }),
  f('filter-028', 'Soft Portrait', 'Portrait',
    'Natural soft portrait with gentle contrast and skin-friendly midtones.',
    { softBlur: 12, shadows: 12, temperature: 6, contrast: 12, clarity: -6, saturation: 4 }, { free: true }),
  f('filter-029', 'Portrait Glow', 'Portrait',
    'Controlled warm portrait glow with refined highlights.',
    { bloom: 14, softBlur: 8, temperature: 10, contrast: 14, shadows: 8, saturation: 6 }, { free: true }),
  f('filter-030', 'Crisp', 'Professional',
    'Crisp detail and mild contrast for product and architecture.',
    { clarity: 20, sharpening: 14, contrast: 18, vibrance: 10, shadows: 4 }, { free: true }),
  f('filter-031', 'Gentle', 'Natural',
    'Gentle contrast without harsh edges for everyday photos.',
    { contrast: 12, shadows: 8, highlights: -6, vibrance: 8, clarity: 6 }, { free: true }),
  f('filter-032', 'Rich Color', 'Natural',
    'Fuller saturation with controlled vibrance for colorful scenes.',
    { saturation: 26, vibrance: 16, contrast: 16, clarity: 8 }, { free: true }),
  f('filter-033', 'Muted', 'Soft',
    'Desaturated muted palette for calm editorial tones.',
    { saturation: -16, fade: 12, contrast: 10, temperature: 2, vignette: 8 }, { free: true }),
  f('filter-034', 'Film Fade', 'Film',
    'Classic film fade with soft grain.',
    { fade: 22, grain: 12, contrast: 12, temperature: 6, vignette: 12 }, { free: true }),
  f('filter-035', 'Analog', 'Film',
    'Analog film touch with grain and mild warmth.',
    { grain: 20, fade: 12, contrast: 14, temperature: 8, vignette: 10, saturation: -4 }, { free: true }),
  f('filter-036', 'Ocean', 'Cool',
    'Cool oceanic cyan-blue grade for water and coastal scenes.',
    { temperature: -14, tint: -6, saturation: 8, contrast: 14, shadows: 10 }, { free: true }),
  f('filter-037', 'Arctic', 'Cool',
    'Cold arctic clarity with crisp blues and firm contrast.',
    { temperature: -20, contrast: 20, clarity: 14, saturation: -4, vignette: 10 }, { free: true }),
  f('filter-038', 'Ember Soft', 'Warm',
    'Soft ember warmth for golden interiors and dusk.',
    { temperature: 22, tint: 6, saturation: 10, contrast: 14, vignette: 10 }, { free: true }),
  f('filter-039', 'Cyan Soft', 'Cool',
    'Soft cyan cast with lifted shadows for modern cool looks.',
    { temperature: -12, tint: -8, shadows: 14, contrast: 12, saturation: 6 }, { free: true }),
  f('filter-040', 'Warm Pop', 'Natural',
    'Warm everyday pop with friendly skin and social-ready color.',
    { temperature: 12, saturation: 18, vibrance: 16, contrast: 16, shadows: 8 }, { free: true }),
  f('filter-041', 'Cinema Ember', 'Cinematic',
    'Warm ember cinematic grade with deep vignette and film grain.',
    { temperature: 16, contrast: 26, vignette: 22, shadows: 6, grain: 10, saturation: 10 }, { tier: 'ai+', cost: 8 }),
  f('filter-042', 'Cinema Teal', 'Cinematic',
    'Teal shadows with warmer highlights for classic cinema color split.',
    { temperature: -10, tint: -6, contrast: 24, vignette: 20, shadows: 8, splitToning: { shadowsHue: 190, shadowsSaturation: 28, highlightsHue: 35, highlightsSaturation: 18, balance: -8 } }, { tier: 'ai+', cost: 8 }),
  f('filter-043', 'Midnight', 'Cinematic',
    'Cool midnight frame with strong vignette and night grain.',
    { temperature: -16, contrast: 28, vignette: 28, grain: 12, shadows: 10 }, { tier: 'ai+', cost: 8 }),
  f('filter-044', 'Golden Cinema', 'Cinematic',
    'Golden cinematic warmth with controlled highlights.',
    { temperature: 20, contrast: 22, vignette: 18, saturation: 12, highlights: -8 }, { tier: 'ai+', cost: 8 }),
  f('filter-045', 'Moody Silver', 'Moody',
    'Desaturated silver mood with firm contrast and soft fade.',
    { saturation: -22, contrast: 22, fade: 12, vignette: 20, grain: 8 }, { tier: 'ai+', cost: 8 }),
  f('filter-046', 'Noir', 'Black & White',
    'Hard noir blacks with high contrast and deep vignette.',
    { monochrome: true, contrast: 40, shadows: -16, vignette: 30, grain: 12, clarity: 10 }, { tier: 'ai+', cost: 8 }),
  f('filter-047', 'Velvet', 'Moody',
    'Velvet soft shadows with gentle cool cast.',
    { shadows: 16, softBlur: 12, contrast: 14, fade: 8, vignette: 16, temperature: -4 }, { tier: 'ai+', cost: 8 }),
  f('filter-048', 'Editorial', 'Fashion',
    'Editorial skin-friendly contrast for fashion stills.',
    { contrast: 20, clarity: 6, temperature: 4, softBlur: 6, saturation: 6, vignette: 10 }, { tier: 'ai+', cost: 8 }),
  f('filter-049', 'Fashion Hard', 'Fashion',
    'High fashion contrast and clarity for runway energy.',
    { contrast: 30, clarity: 14, sharpening: 10, saturation: 8, vignette: 14 }, { tier: 'ai+', cost: 8 }),
  f('filter-050', 'Street Cinema', 'Street',
    'Street cinema grit with cool tone and grain.',
    { contrast: 28, clarity: 16, temperature: -6, grain: 10, vignette: 18, saturation: 6 }, { tier: 'ai+', cost: 8 }),
  f('filter-051', 'Neon Pop', 'Neon',
    'Electric neon magenta-cyan push for night city color.',
    { style: 'neon', saturation: 30, contrast: 24, bloom: 18, temperature: -8, vignette: 16 }, { tier: 'ai+', cost: 8, animated: true }),
  f('filter-052', 'Electric', 'Neon',
    'Intense electric night glow with strong bloom.',
    { style: 'neon', saturation: 34, bloom: 22, contrast: 22, temperature: -12, vignette: 20 }, { tier: 'ai+', cost: 8, animated: true }),
  f('filter-053', 'Dream Film', 'Film',
    'Dreamy film with soft hilation and warm grain.',
    { softBlur: 14, bloom: 16, fade: 12, grain: 10, temperature: 8, contrast: 12 }, { tier: 'ai+', cost: 8 }),
  f('filter-054', 'Film Dust', 'Film',
    'Heavy dusty grain and faded film density.',
    { grain: 28, fade: 16, contrast: 14, temperature: 6, vignette: 14, saturation: -6 }, { tier: 'ai+', cost: 8 }),
  f('filter-055', 'Light Leak', 'Vintage',
    'Warm light-leak edges with soft bloom.',
    { temperature: 22, fade: 18, bloom: 14, saturation: 10, vignette: 22, grain: 8 }, { tier: 'ai+', cost: 8 }),
  f('filter-056', 'Grain', 'Film',
    'Strong film grain texture with balanced contrast.',
    { grain: 30, contrast: 16, fade: 10, temperature: 4, vignette: 12 }, { tier: 'ai+', cost: 8 }),
  f('filter-057', 'Soft Halo', 'Soft',
    'Soft halation bloom for ethereal portraits and lights.',
    { bloom: 26, softBlur: 16, clarity: -12, fade: 10, temperature: 6 }, { tier: 'ai+', cost: 8 }),
  f('filter-058', 'Drama Face', 'Portrait',
    'Dramatic portrait contrast with controlled shadows.',
    { contrast: 26, shadows: -6, vignette: 20, clarity: 10, temperature: 4, saturation: 6 }, { tier: 'ai+', cost: 8 }),
  f('filter-059', 'Window Light', 'Cinematic',
    'Window-light cinema with soft shadow lift.',
    { contrast: 20, shadows: 14, temperature: 6, vignette: 16, softBlur: 4, highlights: -8 }, { tier: 'ai+', cost: 8 }),
  f('filter-060', 'Golden Hour', 'Sunset',
    'Pro golden-hour warmth with rich separation.',
    { temperature: 28, tint: 6, saturation: 14, highlights: -10, shadows: 10, vignette: 12 }, { tier: 'ai+', cost: 8 }),
  f('filter-061', 'Blue Pro', 'Cool',
    'Deeper blue-hour atmosphere with cool grain.',
    { temperature: -20, tint: -6, shadows: 14, contrast: 18, vignette: 16, grain: 6 }, { tier: 'ai+', cost: 8 }),
  f('filter-062', 'Travel Cinema', 'Travel',
    'Travel cinematic grade with clarity and mild vignette.',
    { contrast: 22, vibrance: 14, vignette: 14, temperature: 6, clarity: 10, grain: 4 }, { tier: 'ai+', cost: 8 }),
  f('filter-063', 'Urban Drama', 'Dramatic',
    'Urban dramatic contrast for architecture and streets.',
    { contrast: 34, clarity: 16, vignette: 24, shadows: -8, saturation: 6 }, { tier: 'ai+', cost: 8 }),
  f('filter-064', 'Doc Tone', 'Street',
    'Neutral documentary tone with subtle fade.',
    { contrast: 16, saturation: -10, fade: 6, clarity: 10, grain: 6, temperature: 0 }, { tier: 'ai+', cost: 8 }),
  f('filter-065', 'Music Video', 'Cinematic',
    'Punchy music-video grade with vivid contrast.',
    { contrast: 28, saturation: 20, vibrance: 16, vignette: 18, clarity: 12 }, { tier: 'ai+', cost: 8 }),
  f('filter-066', 'Night Face', 'Portrait',
    'Cool night portrait with lifted face shadows.',
    { temperature: -8, shadows: 18, contrast: 16, softBlur: 6, vignette: 18, grain: 6 }, { tier: 'ai+', cost: 8 }),
  f('filter-067', 'Cinema Pastel', 'Cinematic',
    'Pastel cinematic softness with muted saturation.',
    { fade: 16, softBlur: 10, saturation: -12, temperature: 6, contrast: 12, vignette: 12 }, { tier: 'ai+', cost: 8 }),
  f('filter-068', 'Faded Film', 'Film',
    'Desaturated faded film with soft grain.',
    { saturation: -20, fade: 14, grain: 12, contrast: 16, vignette: 14 }, { tier: 'ai+', cost: 8 }),
  f('filter-069', 'Rich Neg', 'Film',
    'Dense negative-inspired color and contrast.',
    { contrast: 26, saturation: 14, shadows: -4, grain: 10, vignette: 16, temperature: 4 }, { tier: 'ai+', cost: 8 }),
  f('filter-070', 'Matte Cinema', 'Cinematic',
    'Matte cinema blacks with restrained color.',
    { fade: 20, contrast: 18, vignette: 18, saturation: -10, grain: 6 }, { tier: 'ai+', cost: 8 }),
  f('filter-071', 'Hard Film', 'Film',
    'High-contrast film punch with grain.',
    { contrast: 34, grain: 14, vignette: 18, shadows: -10, saturation: 8 }, { tier: 'ai+', cost: 8 }),
  f('filter-072', 'Soft Film', 'Film',
    'Low-contrast soft film for gentle analog moods.',
    { contrast: 8, fade: 18, grain: 12, softBlur: 6, temperature: 4 }, { tier: 'ai+', cost: 8 }),
  f('filter-073', 'Peacock', 'Art',
    'Peacock is a vivid multi-color look built around rich cyan, emerald, violet, magenta, and warm golden tones. It creates strong separation between colorful regions while retaining texture and tonal depth.',
    { saturation: 30, vibrance: 26, contrast: 20, temperature: -6, tint: 10, splitToning: { shadowsHue: 210, shadowsSaturation: 40, highlightsHue: 45, highlightsSaturation: 28, balance: -12 }, clarity: 8 }, { tier: 'ai+', cost: 8, animated: true }),
  f('filter-074', 'Color Burst', 'Art',
    'Explosive controlled color energy for fashion and nightlife.',
    { saturation: 34, vibrance: 28, contrast: 22, clarity: 10, vignette: 12 }, { tier: 'ai+', cost: 8, animated: true }),
  f('filter-075', 'Prism', 'Art',
    'Prism-like color shifts with cool shadows and warm highlights.',
    { contrast: 18, saturation: 22, vibrance: 20, splitToning: { shadowsHue: 260, shadowsSaturation: 30, highlightsHue: 50, highlightsSaturation: 22, balance: 0 }, clarity: 8 }, { tier: 'ai+', cost: 8 }),
  f('filter-076', 'Large Format', 'Professional',
    'Large-format-inspired clarity, depth, and refined dynamic range.',
    { clarity: 26, contrast: 24, sharpening: 14, vignette: 16, shadows: 6, vibrance: 10 }, { tier: 'premium', cost: 12 }),
  f('filter-077', 'Ultra Cinema', 'Cinematic',
    'Ultra cinematic contrast frame with deep vignette.',
    { contrast: 32, vignette: 30, grain: 10, shadows: -6, temperature: -2, saturation: 8 }, { tier: 'premium', cost: 12 }),
  f('filter-078', 'Ultra Detail', 'Professional',
    'Hyper-detail microclarity aesthetic for architecture and product.',
    { clarity: 32, sharpening: 20, contrast: 20, microcontrast: 16, vibrance: 8 }, { tier: 'premium', cost: 12 }),
  f('filter-079', 'Epic Frame', 'Cinematic',
    'IMAX-inspired epic contrast and scale without resolution claims.',
    { contrast: 30, vignette: 26, clarity: 18, shadows: -4, saturation: 10, grain: 6 }, { tier: 'premium', cost: 12 }),
  f('filter-080', 'Grand Cinema', 'Cinematic',
    'Grand cinematic scale with warm vibrance and vignette.',
    { contrast: 28, vignette: 26, temperature: 4, grain: 8, shadows: 6, vibrance: 12 }, { tier: 'premium', cost: 12 }),
  f('filter-081', 'Wide Drama', 'Dramatic',
    'Widescreen dramatic punch for landscapes and streets.',
    { contrast: 34, vignette: 28, clarity: 14, shadows: -8, saturation: 8 }, { tier: 'premium', cost: 12 }),
  f('filter-082', 'Deep Range', 'Professional',
    'Deep dynamic-range inspired tone with protected highlights.',
    { shadows: 18, highlights: -14, contrast: 16, clarity: 12, vibrance: 10 }, { tier: 'premium', cost: 12 }),
  f('filter-083', 'Luxury Face', 'Portrait',
    'Luxury portrait polish with controlled glow.',
    { softBlur: 10, bloom: 12, temperature: 8, contrast: 16, vignette: 14, saturation: 6, clarity: 4 }, { tier: 'premium', cost: 12 }),
  f('filter-084', 'Studio Pro', 'Professional',
    'Studio-balanced grade for controlled lighting setups.',
    { contrast: 20, clarity: 14, sharpening: 10, shadows: 8, vibrance: 10, vignette: 8 }, { tier: 'premium', cost: 12 }),
  f('filter-085', 'Editorial Pro', 'Fashion',
    'Editorial master fashion grade with refined contrast.',
    { contrast: 26, clarity: 12, saturation: 10, vignette: 16, temperature: 2, sharpening: 8 }, { tier: 'premium', cost: 12 }),
  f('filter-086', 'Night Master', 'Night',
    'Night master cool depth with heavy vignette.',
    { temperature: -16, contrast: 24, vignette: 28, grain: 12, shadows: 14, saturation: -4 }, { tier: 'premium', cost: 12 }),
  f('filter-087', 'Neon Master', 'Neon',
    'Maximum neon intensity for cyber night scenes.',
    { style: 'neon', saturation: 36, bloom: 26, contrast: 26, temperature: -10, vignette: 22 }, { tier: 'premium', cost: 12 }),
  f('filter-088', 'Desert Epic', 'Landscape',
    'Desert epic warm drama with clarity.',
    { temperature: 26, contrast: 26, clarity: 16, vignette: 18, saturation: 12, grain: 6 }, { tier: 'premium', cost: 12 }),
  f('filter-089', 'Ocean Cinema', 'Landscape',
    'Oceanic cool cinema for coasts and sky.',
    { temperature: -12, tint: -4, contrast: 22, vignette: 16, saturation: 8, clarity: 10 }, { tier: 'premium', cost: 12 }),
  f('filter-090', 'Mountain', 'Landscape',
    'Mountain grandeur with crisp clarity and cool air.',
    { clarity: 24, contrast: 24, temperature: -4, vignette: 14, shadows: 8, vibrance: 10 }, { tier: 'premium', cost: 12 }),
  f('filter-091', 'Black Glass', 'Black & White',
    'Deep black-glass mono with crushed blacks.',
    { monochrome: true, contrast: 42, shadows: -18, vignette: 32, clarity: 16, grain: 8 }, { tier: 'premium', cost: 12 }),
  f('filter-092', 'Platinum', 'Black & White',
    'Soft platinum mono with gentle fade.',
    { monochrome: true, contrast: 18, fade: 12, grain: 10, vignette: 12, softBlur: 4 }, { tier: 'premium', cost: 12 }),
  f('filter-093', 'Velvet Cinema', 'Cinematic',
    'Velvet soft drama cinema grade.',
    { softBlur: 12, contrast: 22, vignette: 22, fade: 8, temperature: 4, saturation: 6 }, { tier: 'premium', cost: 12 }),
  f('filter-094', 'Director Tone', 'Cinematic',
    'Director-style cool cinematic grade.',
    { contrast: 26, vignette: 24, temperature: -4, tint: -4, grain: 8, saturation: 4, shadows: 6 }, { tier: 'premium', cost: 12 }),
  f('filter-095', 'Festival', 'Cinematic',
    'Festival film frame with warm grain.',
    { contrast: 24, grain: 14, fade: 10, vignette: 18, temperature: 6, saturation: 10 }, { tier: 'premium', cost: 12 }),
  f('filter-096', 'Master Contrast', 'Dramatic',
    'Maximum controlled contrast for graphic drama.',
    { contrast: 40, shadows: -14, vignette: 26, clarity: 14, saturation: 6 }, { tier: 'premium', cost: 12 }),
  f('filter-097', 'Ultra Natural', 'Natural',
    'Ultra-clean natural polish for premium everyday shots.',
    { contrast: 16, clarity: 14, vibrance: 12, sharpening: 10, shadows: 6, temperature: 2 }, { tier: 'premium', cost: 12 }),
  f('filter-098', 'Hyper Portrait', 'Portrait',
    'Hyper-real portrait detail with subtle polish.',
    { clarity: 20, sharpening: 14, contrast: 18, softBlur: 2, temperature: 4, saturation: 6, vignette: 10 }, { tier: 'premium', cost: 12 }),
  f('filter-099', 'Comic', 'Comic',
    'Illustrated comic look with posterized color blocks and ink edges.',
    { style: 'comic', posterizeLevels: 5, edgeAmount: 48, contrast: 26, saturation: 28, vibrance: 16 }, { tier: 'premium', cost: 12 }),
  f('filter-100', 'Sketch', 'Sketch',
    'Pencil-sketch drawing look with line extraction and paper-like tone.',
    { style: 'sketch', monochrome: true, edgeAmount: 72, grain: 16, contrast: 20, fade: 6 }, { tier: 'premium', cost: 12 }),
];
