/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// RESTORED + extended with filter-editor, lens-editor, age, circle-add-discover, sample/$id.
// Image Tools route intentionally removed.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentFailedRouteImport } from './routes/payment-failed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EditRouteImport } from './routes/edit'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdsDottxtRouteImport } from './routes/ads[.]txt'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioVideoRouteImport } from './routes/studio.video'
import { Route as StudioMusicRouteImport } from './routes/studio.music'
import { Route as StudioImageRouteImport } from './routes/studio.image'
import { Route as StudioImageAutoEditRouteImport } from './routes/studio.image.auto-edit'
import { Route as StudioImageCircleRemoveRouteImport } from './routes/studio.image.circle-remove'
import { Route as StudioImageMultiRouteImport } from './routes/studio.image.multi'
import { Route as StudioImageFiltersRouteImport } from './routes/studio.image.filters'
import { Route as StudioImageLensesRouteImport } from './routes/studio.image.lenses'
import { Route as StudioImageFilterEditorRouteImport } from './routes/studio.image.filter-editor'
import { Route as StudioImageLensEditorRouteImport } from './routes/studio.image.lens-editor'
import { Route as StudioImageAgeRouteImport } from './routes/studio.image.age'
import { Route as StudioImageCircleAddDiscoverRouteImport } from './routes/studio.image.circle-add-discover'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SampleIdRouteImport } from './routes/sample.$id'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedMusicRouteImport } from './routes/_authenticated.music'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated.history'
import { Route as AuthenticatedEditorRouteImport } from './routes/_authenticated.editor'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated.chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedProfileSubscriptionRouteImport } from './routes/_authenticated.profile.subscription'
import { Route as AuthenticatedAdminRefundsRouteImport } from './routes/_authenticated.admin_.refunds'

const TrustRoute = TrustRouteImport.update({ id: '/trust', path: '/trust', getParentRoute: () => rootRouteImport } as any)
const TicketsRoute = TicketsRouteImport.update({ id: '/tickets', path: '/tickets', getParentRoute: () => rootRouteImport } as any)
const TermsRoute = TermsRouteImport.update({ id: '/terms', path: '/terms', getParentRoute: () => rootRouteImport } as any)
const SupportRoute = SupportRouteImport.update({ id: '/support', path: '/support', getParentRoute: () => rootRouteImport } as any)
const SuccessRoute = SuccessRouteImport.update({ id: '/success', path: '/success', getParentRoute: () => rootRouteImport } as any)
const StudioRoute = StudioRouteImport.update({ id: '/studio', path: '/studio', getParentRoute: () => rootRouteImport } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({ id: '/sitemap.xml', path: '/sitemap.xml', getParentRoute: () => rootRouteImport } as any)
const SecurityRoute = SecurityRouteImport.update({ id: '/security', path: '/security', getParentRoute: () => rootRouteImport } as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({ id: '/reset-password', path: '/reset-password', getParentRoute: () => rootRouteImport } as any)
const PrivacyRoute = PrivacyRouteImport.update({ id: '/privacy', path: '/privacy', getParentRoute: () => rootRouteImport } as any)
const PricingRoute = PricingRouteImport.update({ id: '/pricing', path: '/pricing', getParentRoute: () => rootRouteImport } as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({ id: '/payment-success', path: '/payment-success', getParentRoute: () => rootRouteImport } as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({ id: '/payment-failed', path: '/payment-failed', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const FeedbackRoute = FeedbackRouteImport.update({ id: '/feedback', path: '/feedback', getParentRoute: () => rootRouteImport } as any)
const FeaturesRoute = FeaturesRouteImport.update({ id: '/features', path: '/features', getParentRoute: () => rootRouteImport } as any)
const FaqRoute = FaqRouteImport.update({ id: '/faq', path: '/faq', getParentRoute: () => rootRouteImport } as any)
const EditRoute = EditRouteImport.update({ id: '/edit', path: '/edit', getParentRoute: () => rootRouteImport } as any)
const CheckoutRoute = CheckoutRouteImport.update({ id: '/checkout', path: '/checkout', getParentRoute: () => rootRouteImport } as any)
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const AdsDottxtRoute = AdsDottxtRouteImport.update({ id: '/ads.txt', path: '/ads.txt', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({ id: '/_authenticated', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AboutRoute = AboutRouteImport.update({ id: '/about', path: '/about', getParentRoute: () => rootRouteImport } as any)
const SampleIdRoute = SampleIdRouteImport.update({ id: '/sample/$id', path: '/sample/$id', getParentRoute: () => rootRouteImport } as any)
const StudioVideoRoute = StudioVideoRouteImport.update({ id: '/video', path: '/video', getParentRoute: () => StudioRoute } as any)
const StudioMusicRoute = StudioMusicRouteImport.update({ id: '/music', path: '/music', getParentRoute: () => StudioRoute } as any)
const StudioImageRoute = StudioImageRouteImport.update({ id: '/image', path: '/image', getParentRoute: () => StudioRoute } as any)
const StudioImageAutoEditRoute = StudioImageAutoEditRouteImport.update({ id: '/auto-edit', path: '/auto-edit', getParentRoute: () => StudioImageRoute } as any)
const StudioImageCircleRemoveRoute = StudioImageCircleRemoveRouteImport.update({ id: '/circle-remove', path: '/circle-remove', getParentRoute: () => StudioImageRoute } as any)
const StudioImageMultiRoute = StudioImageMultiRouteImport.update({ id: '/multi', path: '/multi', getParentRoute: () => StudioImageRoute } as any)
const StudioImageFiltersRoute = StudioImageFiltersRouteImport.update({ id: '/filters', path: '/filters', getParentRoute: () => StudioImageRoute } as any)
const StudioImageLensesRoute = StudioImageLensesRouteImport.update({ id: '/lenses', path: '/lenses', getParentRoute: () => StudioImageRoute } as any)
const StudioImageFilterEditorRoute = StudioImageFilterEditorRouteImport.update({ id: '/filter-editor', path: '/filter-editor', getParentRoute: () => StudioImageRoute } as any)
const StudioImageLensEditorRoute = StudioImageLensEditorRouteImport.update({ id: '/lens-editor', path: '/lens-editor', getParentRoute: () => StudioImageRoute } as any)
const StudioImageAgeRoute = StudioImageAgeRouteImport.update({ id: '/age', path: '/age', getParentRoute: () => StudioImageRoute } as any)
const StudioImageCircleAddDiscoverRoute = StudioImageCircleAddDiscoverRouteImport.update({ id: '/circle-add-discover', path: '/circle-add-discover', getParentRoute: () => StudioImageRoute } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedMusicRoute = AuthenticatedMusicRouteImport.update({ id: '/music', path: '/music', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({ id: '/history', path: '/history', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedEditorRoute = AuthenticatedEditorRouteImport.update({ id: '/editor', path: '/editor', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({ id: '/chat', path: '/chat', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({ id: '/profile', path: '/profile', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedProfileSubscriptionRoute = AuthenticatedProfileSubscriptionRouteImport.update({ id: '/subscription', path: '/subscription', getParentRoute: () => AuthenticatedProfileRoute } as any)
const AuthenticatedAdminRefundsRoute = AuthenticatedAdminRefundsRouteImport.update({ id: '/admin/refunds', path: '/admin/refunds', getParentRoute: () => AuthenticatedRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sample/$id': typeof SampleIdRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/edit': typeof EditRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRoute
  '/trust': typeof TrustRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/editor': typeof AuthenticatedEditorRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/music': typeof AuthenticatedMusicRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/studio/image': typeof StudioImageRoute
  '/studio/image/auto-edit': typeof StudioImageAutoEditRoute
  '/studio/image/circle-remove': typeof StudioImageCircleRemoveRoute
  '/studio/image/multi': typeof StudioImageMultiRoute
  '/studio/image/filters': typeof StudioImageFiltersRoute
  '/studio/image/lenses': typeof StudioImageLensesRoute
  '/studio/image/filter-editor': typeof StudioImageFilterEditorRoute
  '/studio/image/lens-editor': typeof StudioImageLensEditorRoute
  '/studio/image/age': typeof StudioImageAgeRoute
  '/studio/image/circle-add-discover': typeof StudioImageCircleAddDiscoverRoute
  '/studio/music': typeof StudioMusicRoute
  '/studio/video': typeof StudioVideoRoute
  '/profile/subscription': typeof AuthenticatedProfileSubscriptionRoute
  '/admin/refunds': typeof AuthenticatedAdminRefundsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sample/$id': typeof SampleIdRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/edit': typeof EditRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRoute
  '/trust': typeof TrustRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/editor': typeof AuthenticatedEditorRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/music': typeof AuthenticatedMusicRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/studio/image': typeof StudioImageRoute
  '/studio/image/auto-edit': typeof StudioImageAutoEditRoute
  '/studio/image/circle-remove': typeof StudioImageCircleRemoveRoute
  '/studio/image/multi': typeof StudioImageMultiRoute
  '/studio/image/filters': typeof StudioImageFiltersRoute
  '/studio/image/lenses': typeof StudioImageLensesRoute
  '/studio/image/filter-editor': typeof StudioImageFilterEditorRoute
  '/studio/image/lens-editor': typeof StudioImageLensEditorRoute
  '/studio/image/age': typeof StudioImageAgeRoute
  '/studio/image/circle-add-discover': typeof StudioImageCircleAddDiscoverRoute
  '/studio/music': typeof StudioMusicRoute
  '/studio/video': typeof StudioVideoRoute
  '/profile/subscription': typeof AuthenticatedProfileSubscriptionRoute
  '/admin/refunds': typeof AuthenticatedAdminRefundsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sample/$id': typeof SampleIdRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/edit': typeof EditRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRoute
  '/trust': typeof TrustRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/editor': typeof AuthenticatedEditorRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/music': typeof AuthenticatedMusicRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/profile/subscription': typeof AuthenticatedProfileSubscriptionRoute
  '/_authenticated/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/studio/image': typeof StudioImageRoute
  '/studio/image/auto-edit': typeof StudioImageAutoEditRoute
  '/studio/image/circle-remove': typeof StudioImageCircleRemoveRoute
  '/studio/image/multi': typeof StudioImageMultiRoute
  '/studio/image/filters': typeof StudioImageFiltersRoute
  '/studio/image/lenses': typeof StudioImageLensesRoute
  '/studio/image/filter-editor': typeof StudioImageFilterEditorRoute
  '/studio/image/lens-editor': typeof StudioImageLensEditorRoute
  '/studio/image/age': typeof StudioImageAgeRoute
  '/studio/image/circle-add-discover': typeof StudioImageCircleAddDiscoverRoute
  '/studio/music': typeof StudioMusicRoute
  '/studio/video': typeof StudioVideoRoute
}
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/about': { id: '/about'; path: '/about'; fullPath: '/about'; preLoaderRoute: typeof AboutRouteImport; parentRoute: typeof rootRouteImport }
    '/sample/$id': { id: '/sample/$id'; path: '/sample/$id'; fullPath: '/sample/$id'; preLoaderRoute: typeof SampleIdRouteImport; parentRoute: typeof rootRouteImport }
  }
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SampleIdRoute: typeof SampleIdRoute
  TrustRoute: typeof TrustRoute
  TicketsRoute: typeof TicketsRoute
  TermsRoute: typeof TermsRoute
  SupportRoute: typeof SupportRoute
  SuccessRoute: typeof SuccessRoute
  StudioRoute: typeof StudioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SecurityRoute: typeof SecurityRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PrivacyRoute: typeof PrivacyRoute
  PricingRoute: typeof PricingRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  LoginRoute: typeof LoginRoute
  FeedbackRoute: typeof FeedbackRoute
  FeaturesRoute: typeof FeaturesRoute
  FaqRoute: typeof FaqRoute
  EditRoute: typeof EditRoute
  CheckoutRoute: typeof CheckoutRoute
  AuthRoute: typeof AuthRoute
  AdsDottxtRoute: typeof AdsDottxtRoute
  AuthenticatedRoute: typeof AuthenticatedRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SampleIdRoute: SampleIdRoute,
  TrustRoute: TrustRoute,
  TicketsRoute: TicketsRoute,
  TermsRoute: TermsRoute,
  SupportRoute: SupportRoute,
  SuccessRoute: SuccessRoute,
  StudioRoute: StudioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SecurityRoute: SecurityRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PrivacyRoute: PrivacyRoute,
  PricingRoute: PricingRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  LoginRoute: LoginRoute,
  FeedbackRoute: FeedbackRoute,
  FeaturesRoute: FeaturesRoute,
  FaqRoute: FaqRoute,
  EditRoute: EditRoute,
  CheckoutRoute: CheckoutRoute,
  AuthRoute: AuthRoute,
  AdsDottxtRoute: AdsDottxtRoute,
  AuthenticatedRoute: AuthenticatedRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
