-- Idempotent: app_settings (Admin plan/ad control) + page_views (first-party traffic).
-- Safe to re-run on existing production databases.

-- ── public.app_settings ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.app_settings (
  id integer PRIMARY KEY DEFAULT 1,
  plan_visibility jsonb NOT NULL DEFAULT '{"free":true,"lite":true,"plus":true,"pro":true,"studio":true,"business":true}'::jsonb,
  ad_settings jsonb NOT NULL DEFAULT '{"enabled":false,"target":"all","placements":{"home":true,"history":true,"features":true,"pricing":true}}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT app_settings_singleton CHECK (id = 1)
);

-- Ensure columns exist if an older partial table was created
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'app_settings' AND column_name = 'plan_visibility'
  ) THEN
    ALTER TABLE public.app_settings
      ADD COLUMN plan_visibility jsonb NOT NULL DEFAULT '{"free":true,"lite":true,"plus":true,"pro":true,"studio":true,"business":true}'::jsonb;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'app_settings' AND column_name = 'ad_settings'
  ) THEN
    ALTER TABLE public.app_settings
      ADD COLUMN ad_settings jsonb NOT NULL DEFAULT '{"enabled":false,"target":"all","placements":{"home":true,"history":true,"features":true,"pricing":true}}'::jsonb;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'app_settings' AND column_name = 'created_at'
  ) THEN
    ALTER TABLE public.app_settings ADD COLUMN created_at timestamptz NOT NULL DEFAULT now();
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'app_settings' AND column_name = 'updated_at'
  ) THEN
    ALTER TABLE public.app_settings ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();
  END IF;
END $$;

GRANT SELECT ON public.app_settings TO authenticated;
GRANT SELECT ON public.app_settings TO anon;
GRANT ALL ON public.app_settings TO service_role;

ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read app settings" ON public.app_settings;
CREATE POLICY "Anyone can read app settings" ON public.app_settings
  FOR SELECT TO anon, authenticated USING (true);

-- No INSERT/UPDATE/DELETE policies for anon/authenticated — writes only via service_role (admin server fns).

INSERT INTO public.app_settings (id, plan_visibility, ad_settings)
VALUES (
  1,
  '{"free":true,"lite":true,"plus":true,"pro":true,"studio":true,"business":true}'::jsonb,
  '{"enabled":false,"target":"all","placements":{"home":true,"history":true,"features":true,"pricing":true}}'::jsonb
)
ON CONFLICT (id) DO NOTHING;

-- ── public.page_views (first-party traffic) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS public.page_views (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id text NOT NULL,
  user_id uuid NULL,
  pathname text NOT NULL,
  referrer text NULL,
  device_class text NULL,
  country text NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS page_views_created_at_idx ON public.page_views (created_at DESC);
CREATE INDEX IF NOT EXISTS page_views_session_id_idx ON public.page_views (session_id);
CREATE INDEX IF NOT EXISTS page_views_pathname_idx ON public.page_views (pathname);

GRANT INSERT ON public.page_views TO anon;
GRANT INSERT ON public.page_views TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.page_views TO service_role;
-- sequence grants for identity insert
GRANT USAGE, SELECT ON SEQUENCE public.page_views_id_seq TO anon, authenticated, service_role;

ALTER TABLE public.page_views ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can insert page views" ON public.page_views;
CREATE POLICY "Anyone can insert page views" ON public.page_views
  FOR INSERT TO anon, authenticated
  WITH CHECK (true);

-- No SELECT policy for anon/authenticated — traffic aggregates only via service_role admin functions.

NOTIFY pgrst, 'reload schema';
